### ISSUE TITLE
Hashes of downloads

### ISSUE THREAD

**Issue by Findus23** [guysoft/OctoPi#110]
Is it possible to add hashes to the download?
My download stopped multiple times and I had to resume it once with `wget -c`, so I want to check if my files are correct before flashing it.

Update:
The md5-sum of my file is
>6c6659a8ab09bcd99c09cbd5a25315a8  2015-01-31-octopi-0.11.0.zip

**Comment by guysoft** [comment]
I tried to do it in the Jenkins job, but for some reason it would not upload the md5-sum I have there.
You can take a look at:
http://gnet.homelinux.com:8080/job/OctoPi/

I think there is a bug in Jenkins
It says at the end:

    10:15:07 current root dir /nightly
    10:15:07 current root dir /nightly
    10:15:08 transferred 1 files to /
    10:15:08 Transfered 2 files.

But it only transfers the zip and not the md5

**Comment by guysoft** [comment]
Not sure why, Jenkins started uploading the md5 files now. So closing.
