### ISSUE TITLE
Which touchscreen are confirmed working with the Pi2?

### ISSUE THREAD

**Issue by jminardi** [guysoft/OctoPi#130]
I read some issues about touchscreens and the Pi2. Does anyone have a confirmed working setup with a touchscreen and OctoPi on a Pi2?

I am willing to do some testing if someone tells me what to buy, what to test, and what to report. I currently have Pi2s and the PiScreen from ozzmaker.

**Comment by guysoft** [comment]
The two we mainly test 
Adafruit PiTFT
Watterott RPi-Display
There seems to be a report how to fix it on the raspberrypi2:
https://github.com/guysoft/OctoPi/issues/91

**Comment by guysoft** [comment]
Answered, closing.
