### ISSUE TITLE
OctoPiPanel. is it only supported with adafruit pitft

### ISSUE THREAD

**Issue by Bigfellas** [guysoft/OctoPi#131]
Can you tell me does you build allow the us of any other touch screen. Have borrowed a Waveshare spot pear V3 and was wondering if it will work. Or should I just go ahead and buy a Adafruit.
Thanks
Matt

**Comment by guysoft** [comment]
It also works with rapi-display by watterott.
Where are the drives for your "Waveshare spot pear V3" located I can't find them when I search.

**Comment by MolarAmbiguity** [comment]
@guysoft there are drivers for the Waveshare Spot Pear V3 here: https://github.com/swkim01/waveshare-dtoverlays

**Comment by Bigfellas** [comment]
I have ordered a Pitft, So don't go to too much trouble. I have been playing around with a friends Waveshare and there is not a lot of support out there. So I spent the extra.

Thanks
Matt

**Comment by MolarAmbiguity** [comment]
Yeah, the manufacturer (waveshare) doesn't support their product very well. Your are probably better off with someone else.

**Comment by guysoft** [comment]
Closing since this seems to be nothing we will not do in this case (unless someone with access to the hardware is up for it).
