### ISSUE TITLE
Freeze during M105 command

### ISSUE THREAD

**Issue by tderensis** [guysoft/OctoPi#136]
Octopi freezes when I print and then continues after about 30 seconds later. Right before the freeze I see the gcode M105*29. I checked the uploaded gcode and it is not there, so octopi must be injecting it. Is this normal?

I am using Printrbot Simple metal with rev F circuit board. Octoprint version 1.2.4. Pi B+ is running on a 1A supply with the printer plugged into one of the 4 usb ports and a wifi dongle attached through a powered usb hub. I have not seen this behavior when using other computers, only when running octopi.

**Comment by guysoft** [comment]
You should post this in the OctoPrint issue tracker. OctoPi does not manipulate the gecode.
