### ISSUE TITLE
bananapi-m1 octoprint automatic updates not working

### ISSUE THREAD

**Issue by alejandrosela** [guysoft/OctoPi#137]
It might be that in future releases this will be solved as the latest version was not working due to a corrupted file #126, so for the time being, in cases somebody wants to perform an update on the bananapi-m1 release, there is an issue with the permissions of one folder. I solved this by changing these permissions as per:
sudo chown -R pi.pi .git/logs/refs/heads/

Hope it helps!

**Comment by guysoft** [comment]
You must have done a git opration as root and that is what has trigged the error. This has been fixed now with:  https://github.com/guysoft/OctoPi/commit/2cd53c44bf6242f9d68ddac0b2b9d471b2e69866
