### ISSUE TITLE
Code 127 on timelapse

### ISSUE THREAD

**Issue by 3DMuse** [guysoft/OctoPi#140]
Sorry if I am posting this in the wrong area.  I am running 1.2.4 and I keep getting code 127 when I try to do a time lapse.  

Rendering of timelapse glass_clip_front_2_20150827030627.mpg failed with return code 127

/usr/bin/avconv: error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory

Thanks for any help

**Comment by digas** [comment]
Check this command:

ldconfig -p | grep libSM.so.6
If it doesn't outpu anything 
Try:

apt-get install libsm6

Hope this helps you

**Comment by guysoft** [comment]
@digas Is that package needed for a certain camera?

**Comment by guysoft** [comment]
Old, closing,  also OctoPrint issue
