### ISSUE TITLE
OctoPi can not use Raspberry Pi camera，how to use it？

### ISSUE THREAD

**Issue by dilon007** [guysoft/OctoPi#154]
I install a CSI Camera in raspberry and use OctoPi Image。
but now I can‘t use CSI Camera:
1.  set enable camera in raspi-config
2.  apt-get update &  apt-get upgrade
3.  input cammod ：raspistill -o image.jpg -rot 180
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates

If I use raspberry image, the camera can be used。
how to use raspberry camera in octopi？

**Comment by guysoft** [comment]
1. Pi camera should work out of the box, without using rpi-config
2. raspistill would NOT work because MJPG-Streamer will take control of it
3. That you have AT LEAST 2A power supply, and A GOOD USB CABLE.
4. Also people reported a similar error when the camera cable was broken.

Duplicate of #31
