### ISSUE TITLE
BED SETUP

### ISSUE THREAD

**Issue by dubiousp** [guysoft/OctoPi#157]
Good morning really new to all of this but setup the PI and works like a dream, the only thing is do I set the bed dims in the slicer or I see in Octopi there is an option to front left or centre. Could someone perhaps help me in pure simple terms

Thanks in advance

**Comment by guysoft** [comment]
1. This is an OctoPrint issue so I am closing this
2. The bed settings are "Settings" in the "Printer Profiles"
