### ISSUE TITLE
Android not resolving Zeroconf

### ISSUE THREAD

**Issue by smartroad** [guysoft/OctoPi#16]
Hi, I have started to get OctoPrint working. Accessing it via Windows (once Bonjour was installed) works a treat. I get to see the video from the webcam, however on Android (Chorme and native) I have to enter the IP address as it won't find the address via Bonjour, so when I go to control tab I don't get an image.

I did put this onto the OctoPrint bugtracker but it was suggested here would be a better place. A suggestion from there was to use a relative address rather than using the octopi.local. I found the place in the settings for the webcam but have been unable to change the url and still have it working. Is there anything else I can try?

I used the latest SD Card image to install.

**Comment by foosel** [comment]
Yup. If anything that should be filed against the Android bug tracker, nothing OctoPi can do here.
