### ISSUE TITLE
Hanging web controls since 1.2.8 update

### ISSUE THREAD

**Issue by jbitterly** [guysoft/OctoPi#179]
I run octopi on a raspberry pi 2 with a pi cam and edimax wifi adapter connected to a Craftbot via USB.  I updated to 1.2.8 using the plugin bugfix yesterday and have had very poor response from the web controls since.  

For instance, when preheating my bed and not printing it normally shuts off every 10 minutes as a safety precaution.  I have to toggle it back on every 10 minutes several times to get to temperature but since the update the printer does not respond to temperature set commands on the octopi web form if it was left idle for 10 minutes.  Sometimes I can switch to the control tab and home the z axis to get a response and then go back to temperature and set it.  Sometimes I have to click the home buttons several times to make this happen.  

I have a poor wifi signal through the edimax adapter because I get extremely poor webcam streaming.  It is the location of the printer and I can't really fix that at the moment but controls were working perfectly in 1.2.7.  The only thing changed since the last working config is the version update.  I also use a modified driver for the wifi adapter that disables its power saving feature and prevents it from not responding.  That has been working fine as well and still does because that bug would cause me to be unable to ssh in to the pi.

**Comment by guysoft** [comment]
This should be posted in the OctoPrint issue tracker at: https://github.com/foosel/OctoPrint/issues/
This issue tracker is for OctoPi issues, the operating system, not OctoPrint, the software that runs on it.
