### ISSUE TITLE
service haproxy start - failed

### ISSUE THREAD

**Issue by SFrav** [guysoft/OctoPi#182]
After installing OctoPi (0.12) for a B model I couldn't log in to the web interface. Troubleshooting, I suspect it's the haproxy daemon. Running `<service haproxy start>` returns an error :unable to start /usr/local/sbin/haproxy (Exec format error) Failed.
I tried tweaking /etc/haproxy/haproxy.cfg and running `<service haproxy restart>`

**Comment by guysoft** [comment]
What version of OctoPi did you install ?

**Comment by SFrav** [comment]
Version is in the opening comment - 0.12, the current version.

**Comment by SFrav** [comment]
A reinstall on a different card solved this.
