### ISSUE TITLE
Not launching on Jessie

### ISSUE THREAD

**Issue by kd7eir** [guysoft/OctoPi#185]
Anyone having luck with the latest nightlies built on Jessie? I cannot get octoprint to start with any of the Jessie nightlies. If I type sudo service octoprint start I get the following error -

Failed to start octoprint.service: Unit octoprint.service failed to load: No such file or directory.

I tried to update and I got the following error at the end -

Failed to restart octoprint.service: Unit octoprint.service failed to load: No such file or directory.﻿

**Comment by guysoft** [comment]
What nightly are you using? Put the date of it

**Comment by kd7eir** [comment]
2015-12-19_2015-11-21-octopi-jessie-0.13.0

**Comment by guysoft** [comment]
Try the one from today:
2016-01-06_2015-11-21-octopi-jessie-lite-0.13.0.zip
I don't remember the state of OctoPi a month ago.

**Comment by kd7eir** [comment]
That worked. Thank you.
