### ISSUE TITLE
changing/adding to the web interface?

### ISSUE THREAD

**Issue by xal3xhx** [guysoft/OctoPi#186]
i was wondering if it was possible to add a new page to the web server. i have a folder with a simple web page in it like a index.html i want to make that run on the same server as the octoprint. like octopi.local/folder any ideas.

**Comment by guysoft** [comment]
You will need to modify OctoPrint. Its running on an internal flask server. It might be easy using plugins.
Alternatively install a webserver on OctoPi and put it there.

**Comment by guysoft** [comment]
Closing, you can look at plugins for this such as http://plugins.octoprint.org/plugins/touchui/
or https://github.com/markwal/OctoPrint-ScreenSquish
