### ISSUE TITLE
$HAPROXY in /etc/default/haproxy and /etc/init.d/haproxy must match

### ISSUE THREAD

**Issue by ariporad** [guysoft/OctoPi#192]
Hi! Thanks for the awesome project!

It would appear that the path to HAProxy must match in `/etc/default/haproxy` and `/etc/init.d/haproxy`, because `/etc/init.d/haproxy` checks for HAProxy existence before loading `/etc/default/haproxy`.

Also, It would be really helpful if there was a comment in `/etc/init.d/haproxy` saying to change the config in `/etc/default/haproxy`.

I couldn't figure out where those files come from, otherwise I would submit a PR.

Thanks!

**Comment by guysoft** [comment]
@foosel is this relevant? I am not sure what exactly its about.

Don't ask for PR to PR :) 
I won't pull anything, but if it solves a problem and does not create a new one I will

**Comment by foosel** [comment]
AFAIK the init scripts and default files for haproxy are not under OctoPi's control but come from the haproxy Debian package that gets installed. So that should ideally be fixed upstream, not here.

**Comment by guysoft** [comment]
You can post a bug report to HAProxy package maintainer at:
https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=haproxy;dist=jessie

@kaplanlior Any idea who we can report this to?

**Comment by guysoft** [comment]
Is this still relevant? Closing if no reply
