### ISSUE TITLE
Timelapse not work on nightly 2015-11-21-octopi-jessie-lite-0.13.0

### ISSUE THREAD

**Issue by KissmanCZ** [guysoft/OctoPi#194]
Hi, due to my camera hardware (Genisu LightCam 1020) i must use nightly builds. But in build 2015-11-21-octopi-jessie-lite-0.13.0 timelapse not work.

I can set up timelapse, but no timelapse was captured and no file after print.

**Comment by KissmanCZ** [comment]
I just investigate some new info... is there any "timelapse" log, where can I look? My temp jpg images are created during the print inside folder "timelapse/tmp", but no video generated after print...

**Comment by guysoft** [comment]
We are already on  2016-02-09, this issue is likely fixed due to kernel changes on raspbian, is it working for you now @KissmanCZ ?

**Comment by guysoft** [comment]
Closing because no reply
