### ISSUE TITLE
getting invalid user error when building octopi

### ISSUE THREAD

**Issue by RTLflat** [guysoft/OctoPi#195]
i put my zipped image in ~/OctoPi/src/image

and used following commands from within ~/OctoPi/src

sudo modprobe loop
sudo bash -x ./build

runs for a bit then i get
/bin/chown: invalid user: 'pi:pi'

this happens after the execute_chroot_script part shuffles things around a bit. do i need to create a user pi on linux machine im building on?

**Comment by guysoft** [comment]
no, user pi is part of the raspbian system that is in the chroot. Can you
post the entire build process?

**Comment by guysoft** [comment]
Closing due to no reply
