### ISSUE TITLE
Static IP on wired Ethernet..

### ISSUE THREAD

**Issue by tobiasbischoff** [guysoft/OctoPi#202]
Hi, 

somehow I cannot desable dhcp and set  a static IP for the fixed LAN. Is /etc/network/interfaces ignored somehow?

**Comment by guysoft** [comment]
What version of OctoPi are you using?
Can you follow the boot sequence on a screen and see if it tries to use
DHCP to get an address?

**Comment by waynemichel** [comment]
You now need to edit /etc/dhcpcd.conf and ignore /etc/network/interfaces.

howto: http://www.circuitbasics.com/how-to-set-up-a-static-ip-on-the-raspberry-pi/

**Comment by foosel** [comment]
And in case you are wondering why: https://www.raspberrypi.org/blog/another-raspbian-desktop-user-interface-update/

Personally, I'm not a big fan of `dhcpcd`, `/etc/network/interfaces` works just fine, especially headless, but removing that stuff by default would confuse a lot of people probable ("Why doesn't X work like in this Raspberry Pi tutorial over here?!")

**Comment by jrpmedia** [comment]
I cannot see _/etc/network/interfaces_ on the USB card when it is in my Mac OSX.
Even if I _show invisible_ files.
Is there another way, on Mac, to access this file location on the USB card?

**Comment by guysoft** [comment]
See https://github.com/guysoft/OctoPi/issues/219 , there are instructions how to set it up today with Jessie.

**Comment by guysoft** [comment]
Any news on this? Is it working?

**Comment by guysoft** [comment]
Closing due to no reply

**Comment by IT-Mase** [comment]
Hi !
I had the same issue ...
Found an answer, for last version which is under raspbian bookworm [here](https://www.abelectronics.co.uk/kb/article/31/set-a-static-ip-address-on-raspberry-pi-os-bookworm) !
It worked like a charm for me !

Ciao !

**Comment by guysoft** [comment]
Thanks @IT-Mase if you want you can include it in the wiki under network:
https://github.com/guysoft/OctoPi/wiki/FAQ

**Comment by SlyLaM** [comment]
I don't know how it has to be done but I tried.
you can check here:
https://github.com/guysoft/OctoPi/wiki/Set-Static-IP-on-wired-connection

Thanks

**Comment by guysoft** [comment]
@SlyLaM good enough. Thanks!
