### ISSUE TITLE
Octoprint crashing when trying to update

### ISSUE THREAD

**Issue by I-am-me** [guysoft/OctoPi#204]
I recently installed OctoPi 0.12 on my raspberry pi, it comes with OctoPrint 1.2.2.

When I try to update to OctoPrint 1.2.9 it says there was an error.
After I reboot and try to access the OctoPrint UI I get a 503 error saying "Service Unavailable"

I am still able to access the raspberry pi through SSH, I tried restarting OctoPrint from the pi but it still won't work.

**Comment by markwal** [comment]
What does ~/.octoprint/logs/octoprint.log say?

**Comment by I-am-me** [comment]
I forgot to copy the logs before re-rewriting my SD card. 
I just tried to see if it would crash and it worked, so I guess it was a problem on my end. If it happens again I'll let you know.

Thanks anyway
