### ISSUE TITLE
"Load and print" button broke in latest update

### ISSUE THREAD

**Issue by giantpune** [guysoft/OctoPi#213]
I have octopi running with the gpx plugin.  Just now I received an update for "OctoPrint: 1.2.10".  After that update, the octopi restarted.  Now I can list the gpx files on my sd card as before, but clicking the little "Load and print" button does nothing.  I have to press the buttons on the front of my printer and browse to the file to print it like some sort of caveman.

**Comment by guysoft** [comment]
Hey,  
You better post this in the OctoPrint issue tracker. 
https://github.com/foosel/OctoPrint/issues

**Comment by giantpune** [comment]
I'll try, but their issue tracker says not to post issues if they have to do with octopi.

**Comment by giantpune** [comment]
@guysoft is there an easy way in octoprint to roll back to 1.2.9 until the fix is identified and released by whoever needs to fix it?

**Comment by guysoft** [comment]
1. This is an OctoPrint issue. The update system belongs to OctoPrint. Therefore its not an OctoPi issue.
2. I am not sure what the effects to rolling back would be, I suggest you ask that there too.

**Comment by jminardi** [comment]
@giantpune To roll back octoprint you just need to checkout whichever version you want in the OctoPrint src directory.

ssh into the pi
`cd /home/pi/OctoPrint && git checkout 1.2.9`

**Comment by guysoft** [comment]
Looks like its fixed on OctoPrint's end
