### ISSUE TITLE
not recognizing RPI camera

### ISSUE THREAD

**Issue by dsolthesoul** [guysoft/OctoPi#216]
hey..
got the RPI camera moudle and plug it in... but for some reason in the octopi it wont show!

tryed to SSH and used "raspistill" and everything works fine and i get a picture

this is my octopi.txt file

camera="raspi"
camera_raspi_options="-x 1920 -y 1080 -fps 30"

any idea why? or how to fix that ?

**Comment by guysoft** [comment]
What OctoPi version are you using?
What RaspberryPi are you using?

**Comment by dsolthesoul** [comment]
OctoPrint: 1.2.10 
RaspberryPi 1 (2011)

**Comment by foosel** [comment]
Octo**Pi** version. You gave the Octo**Print** version.

`cat /etc/octopi_version`

**Comment by dsolthesoul** [comment]
ohh.. didnt know its different

Pi version - 0.12.0

**Comment by WZ9V** [comment]
Are you sure you have the cable plugged in the right way?  It's easy to get that ribbon cable backwards and that would cause what you are seeing.  I think you can also go straight into the webcam server as octopi.local:8080 which is helpful for troubleshooting camera issues.  Once you have that working it's usually all good in OctoPrint.

**Comment by guysoft** [comment]
Please use 0.13.0

**Comment by dsolthesoul** [comment]
yea.. it an old problame, been fixed for me when 0.13.0 come out

**Comment by foosel** [comment]
Problem reported as fixed.
