### ISSUE TITLE
Some settings pages don't render correctly on Macs

### ISSUE THREAD

**Issue by 040medien** [guysoft/OctoPi#221]
Most of the right hand settings pages remains white until I select some text. This happens on Chrome (no Extensions) an Safari running on OS X 10.11.3.﻿

![settings page](https://cloud.githubusercontent.com/assets/115072/14435817/8c316144-ffce-11e5-9270-af1efe11ab5f.PNG)
![after blindly selecting text](https://cloud.githubusercontent.com/assets/115072/14435818/8c328556-ffce-11e5-9eb4-f029d2f945b2.PNG)

**Comment by markwal** [comment]
This, if it is a bug, is in OctoPrint, not in the script that makes a Raspbian image out of it (octopi).  The repo for that is https://github.com/foosel/OctoPrint.

**Comment by markwal** [comment]
I do not see this occur on either Chrome or Safari on OS X 10.11.3 in either OctoPrint 1.2.10 or OctoPrint 1.3.0-devel.  Though I do have plugins, in particular, ScreenSquish, which might change this behavior.

**Comment by guysoft** [comment]
Not related to OctoPi, use https://github.com/foosel/OctoPrint
