### ISSUE TITLE
Webcam Live Stream Doesn't Autostart

### ISSUE THREAD

**Issue by tenten8401** [guysoft/OctoPi#240]
Hey there, Running OctoPi 0.13 and my Logitech USB webcam doesn't autostart with OctoPi. I reboot the system, w/ webcam plugged in, "OctoPrint server not running, SSH blablabla". If I unplug my webcam, It will start up the streaming server and work perfectly.

For the reference I have a 2.5A power supply hooked up which should be more than enough current.

**Comment by guysoft** [comment]
What rasperrypi and how much amp is your power supply?

**Comment by tenten8401** [comment]
RPi2 with 2.5A power supply

-Isaac
On 7/2/2016 10:12:21 AM, Guy Sheffer <notifications@github.com> wrote:
What rasperrypi and how much amp is your power supply?

**Comment by guysoft** [comment]
Hey, did you solve the issue? You closed it with no explanation
