### ISSUE TITLE
Unable to get Chromium installed to get OctoPiPanel working in a 'kiosk' mode

### ISSUE THREAD

**Issue by TimVa** [guysoft/OctoPi#247]
Hello,
I have been following a lot of guides online, but none seem to have a fitting answer to my issues.  
Setup : RPI3/RPi 7" Touchscreen/OctoPi 0.13 (Jessie Lite) 
(the real official screen, as I have seen a lot of people being confused about this : [https://www.raspberrypi.org/blog/the-eagerly-awaited-raspberry-pi-display/]

Does it work? Does it work on Rpi3?
A bit more clarity in the 'scripts' might help here also.  

Guide followed, but turns bad @ step 4 : [https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser-(OctoPi-or-Jessie-Light)](url)

Willing to help here, with testing on Rpi2/Rpi3 and RpiTouchscreen7"

Keep up the excellent work
T.

**Comment by guysoft** [comment]
Please post in the OctoPiPanel issue tracker
https://github.com/jonaslorander/OctoPiPanel/issues
