### ISSUE TITLE
OctoPi.local works, but 192.168.250.1 does not

### ISSUE THREAD

**Issue by raspiuser6969** [guysoft/OctoPi#253]

**Comment by guysoft** [comment]
What output do you get if you ping octopi.local ?

**Comment by raspiuser6969** [comment]
I fixed the problem: Wrong IP
Thanks anyway!


On Aug 4, 2016, at 8:50 AM, Guy Sheffer <notifications@github.com> wrote:

What output do you get if you ping octopi.local ?
