### ISSUE TITLE
cannot pause print with gcode

### ISSUE THREAD

**Issue by hackermagnet** [guysoft/OctoPi#255]
I have a gcode file to be executed before each print (to clean my nozzle and prepare the surface for printing) and I use M0 command to pause the printing process inside this file.
Since the last update these M0 commands are not executed properly. The message after M0 is not displayed on the screen, the next command (M104) is exexuted without resuming print and I have to resume print from octoprint to execute the next G1 commands.

Also when I was able to pause my printer with M0 command I had to resume with octoprint. Other programs allow me to resume with the rotary encoder on my LCD screen.
What could I do to slove this?
Thank you,
John

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi issue. Please post it at: 
https://github.com/foosel/OctoPrint/issues
