### ISSUE TITLE
1.3.0 Breaks Creator Pro printing

### ISSUE THREAD

**Issue by jackpine63** [guysoft/OctoPi#285]
Printer: Flash Forge Creator Pro dual extruder, Sailfish firmware
GPX: 2.5.5
Slicer: slic3r

After upgrading OctoPi to 1.3.0, when I try to do a print, the temperatures are set on the wrong tool.  Instead of setting the bed temperature to 70, it will set extruder 0 to 70.  Rerun it, and it might set that on extruder 1 instead.  This happens with new or existing gcode files.  I didn't let it run long enough to see what happens after that.  I backed down to 1.2.18 and all is working again.  Not sure if this has to be fixed in OctoPi or GPX, but since upgrading OctoPi broke it...

If you need support materials, just let me know what you need.

**Comment by guysoft** [comment]
This is an octoprint issue, please post it in the OctoPrint issue tracker:
https://github.com/foosel/OctoPrint
