### ISSUE TITLE
Reenable SSH connection by default

### ISSUE THREAD

**Issue by guysoft** [guysoft/OctoPi#286]
The upcoming nightly is going to be based on ``2016-11-25`` which has 
```
  * SSH disabled by default; can be enabled by creating a file with name "ssh" in boot partition
  * Prompt for password change at boot when SSH enabled with default password unchanged
```
[source](http://downloads.raspberrypi.org/raspbian/release_notes.txt) 

After building we can figure out how to make this sane again. Comments on how to do that would be helpful

**Comment by guysoft** [comment]
Strange, on fullpageos nightly it seems to work - anyone can confirm it works for them?

**Comment by foosel** [comment]
SSH is disabled again by default since the merge of #313
