### ISSUE TITLE
Pi Zero 1.3 and Pi Cam v2 not working with OctoPi 0.13

### ISSUE THREAD

**Issue by themitch22** [guysoft/OctoPi#291]
I flashed the OctoPi 0.13 image on a pi zero 1.3 with a pi cam v2, enabled camera, expanded file system, rebooted. There's no camera at all. 

Installed Python, PIP, OctoPrint, etc on a stock Raspbian Jessie (with Pixel) and the camera works fine (but has a ton of steps and the camera service doesn't start on start up.

Is there a driver issue with the version of Jessie you use to make the most recent disk image?

**Comment by guysoft** [comment]
The one it says, there is a date.

You can the nightly and see if it improves.

**Comment by themitch22** [comment]
The nightly build worked for the pi cam! thanks!
