### ISSUE TITLE
[Request] Setup for using your own logos on graph and timelapse video

### ISSUE THREAD

**Issue by henrikkoch** [guysoft/OctoPi#298]
Please make it possible to put your own logo on both the Temperature graph and on the timelapse videos. Its very easy just to exchange the files but on every update this these changes are lost.

The need for own logos are when your print something for others f.ex. on 3DHubs Then I can be a good thing to "brand" it with your hub name.

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/

**Comment by foosel** [comment]
As already mentioned, wrong bug tracker.
