### ISSUE TITLE
[Request] User programmable toggle buttons in UI

### ISSUE THREAD

**Issue by henrikkoch** [guysoft/OctoPi#300]
I world like to have some uset programmable buttons (toggle) that can be controller from the webpage and that the user can use to map to a I/O pin. This could make it possible to turn light on/off and external fan on/off

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/

**Comment by KairuByte** [comment]
This can already be accomplished with the System Command Editor plugin to a certain extent. http://plugins.octoprint.org/plugins/systemcommandeditor/

Alternatively you could use Custom Controls if you wanted it in the control section. http://plugins.octoprint.org/plugins/customControl/

**Comment by foosel** [comment]
As already mentioned, wrong bug tracker and already possible.
