### ISSUE TITLE
Prints Freezing and leaving heaters on in 1.3.1 

### ISSUE THREAD

**Issue by hebs** [guysoft/OctoPi#303]
I am in a large 3d printing channel on slack, specifically for drone racing. Several of us use octoprint, and have been for months. Everyone updated to 1.3.1 and I have at least 5 people reporting prints freezing and leaving heaters on. I didnt think much of it until it just happened to me. I have put about 30kg through this machine, with octoprint, same fw, same hardware, etc... and this is the first freeze ive had.

**Comment by hebs** [comment]
It just happened again: http://pastebin.com/mVSabKFy

**Comment by guysoft** [comment]
This is being handled in OctoPrint issue tracker

**Comment by N3X15** [comment]
Issue ID?
