### ISSUE TITLE
How to read 3D printer output ?

### ISSUE THREAD

**Issue by GH89** [guysoft/OctoPi#307]
I am trying to communicate with my 3D printer using Raspberry Pi via serial, pretty much in the same way as OctoPi does. Basically, what I am doing is to write a python script that uses the pyserial library and sends out commands to the 3D printer like the M105  link - http://reprap.org/wiki/G-code

I am having the following issues:
1. What the printer responds back, is not understood by the Pi and it comes out as gibberish.
While if I send the same commands from my laptop using the serial connection, I can read the values.
2. The new request interrupts the ongoing print and resets the printer. this happens both with the pi as well as the laptop.

Clearly, both these problems do not occur while using OctoPi. What I am I doing wrong here ? 

I am using an Ultimaker 2 Extended + with Cura 2.3 

Thanks

**Comment by guysoft** [comment]
@foosel Any hints? A nudge perhaps?

**Comment by foosel** [comment]
I cannot add anything here that wasn't already mentioned [in the thread @GH89 opened on the mailinglist on the exact same topic](https://groups.google.com/forum/#!topic/octoprint/0vn2XS1qJVo) :)

**Comment by GH89** [comment]
Thanks guys. i am looking into the feedback that has been provided on the group.
