### ISSUE TITLE
[REQUEST] OctoPi + Raspbian PIXEL anytime soon? 

### ISSUE THREAD

**Issue by bolsoncerrado** [guysoft/OctoPi#311]
Ditto ;)

Thanks!

**Comment by guysoft** [comment]
You can already build OctoPi with a pixel image base image.

**Comment by bolsoncerrado** [comment]
you mean you won't dist it prebuilt for the less tech savy? ;)

also, does this mean everything retains compatibility on Pixel?

**Comment by guysoft** [comment]
1. No i won't, because its not recommended for non-tech-savvy people to run an install that. Pixel has more moving parts, such as a gui and lets them install applications that would clash with the OctoPrint instance. Before the lite image came a long we had more complaints, not less.
2. Yes
