### ISSUE TITLE
Upload to SD greyed out; Monoprice Mini Select

### ISSUE THREAD

**Issue by chevyfried** [guysoft/OctoPi#322]
Attached all the logs.  Using a Monoprice Mini Select.  I have the latest 0.13 build of octoprint.

Upload to SD greyed out.

[octoprint (1).zip](https://github.com/guysoft/OctoPi/files/824765/octoprint.1.zip)

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi issue, please report it to the OctoPrint issue tracker:
https://github.com/foosel/OctoPrint/
