### ISSUE TITLE
upload the timelapse automatically to cloud drive?

### ISSUE THREAD

**Issue by nowkillkennys** [guysoft/OctoPi#324]
upload the timelapse automatically to cloud drive? is it possible? maby as a plugin?

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi issue, please use the OctoPrint issue tracker:
https://github.com/foosel/OctoPrint/issues/

**Comment by nowkillkennys** [comment]
im a octopi user

**Comment by guysoft** [comment]
That doesn't change the fact that the issue you reported is a OctoPrint
issue. That is, the software that controls the timelapse creation and
plugins is part of the OctoPrint software. If you want such software to be
written, you need to move things in the right tracker.
