### ISSUE TITLE
OctoPi print failure

### ISSUE THREAD

**Issue by breadfan13** [guysoft/OctoPi#334]
Hello having issue with OctoPi, was working great prior to last night. Now when I attempt a print my printer does it's usual homing,nozzle wipe, then auto level sequence. but when i get to the final probe point the printer just stops moving and octoprint reports a communication error after several minutes. I have tried using both Octoprints onboard slicer as well as loading gcode from Cura on my computer and i get the same result. I've attached my log file (with ip's redacted) and a screen shot of octoprint terminal. OctoPrint is connected to a Lulzbot Taz6 printer and is running on a Raspberry Pi 3 with a 2.5a power supply. This install was previously working and I haven't made any changes or installed new plugins. I've also tried manually setting the baud to 11500 and manually setting the port to /dev/ttyAM0 as instructed on lulzbot's website. When I manually specify these parameters, I cannot connect to the printer. Settings on Auto connect successfully everytime. 

I've tried to be as thorough as possible and include as much information as I know to include. My Serial.log file is blank. I did delete that log and attempt to generate a new one but the file remains empty. 

Any help would be greatly appreciated. Thank you for reading my post.

[octoprint-redacted.txt](https://github.com/guysoft/OctoPi/files/886620/octoprint-redacted.txt)
![screen shot](https://cloud.githubusercontent.com/assets/19809432/24565064/3e7b7e0a-1619-11e7-81cc-f48b65b6d162.jpg)

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi issue, please post it to the OctoPrint issue tracker at:
https://github.com/foosel/OctoPrint/issues/
