### ISSUE TITLE
TFT Touchscreen GUI?

### ISSUE THREAD

**Issue by Cribstone** [guysoft/OctoPi#34]
Support for TFT Touchscreens like the PiTFT would be great for basic controls, emergency stops, sensor calibration etc...  So rather than having to log back into the server every time you need to make a basic change, you could add something like 6 buttons on a touchscreen GUI.

**Comment by tiagojanz** [comment]
Hi, 
Could you please add support to Egalax touchscreen?

Its a pain to compile the kernel each time I switch to a new img. It takes all day!!!!
I can give you all my steps ,  work 100% every time I do it.

And yes of course I'll test it.

**Comment by guysoft** [comment]
Compiling our own kernel might have other side effects,  but willing to give it a try. Can you provide instructions with the exact commands used ti build your touchscreen support?

It might not make it to 0.11.0, but will be added to 
the nightly that comes after it.

**Comment by guysoft** [comment]
See above comment, also can you please open a seprate issie for your screen?
