### ISSUE TITLE
Octopi enterprise wifi

### ISSUE THREAD

**Issue by ozkalt** [guysoft/OctoPi#344]
Hi everyone!
I am using Raspberry Pi 3 with Octopi. I have connected wifi but I need to connect to enterprise wifi. I have changed wpa_supplicant.conf and interfaces files. It does not help to connect wifi. Does anybody have this situation?

**Comment by guysoft** [comment]
What does enterprise WiFi mean?

**Comment by bardiir** [comment]
Probably something with a certificate authentication like 802.1X - but I'm unsure if this really is an issue with OctoPi, this is probably more likely something that would need to be solved in the underlying linux distribution.

**Comment by ozkalt** [comment]
Enterprise WiFi means enterprise network. I mean, I have tried to connect using network of Campus. That network is like "eduroam".

**Comment by ozkalt** [comment]
I solved the problem using another methods. You can use this way: https://gist.github.com/chatchavan/3c58511e3d48f478b0c2
