### ISSUE TITLE
Multiple Serial Port OctoPrint

### ISSUE THREAD

**Issue by OctoConfused** [guysoft/OctoPi#346]
i am trying to run four 3d printers off one computer. i can log on to my otcoprint web page for each port 
just fine if i put usb0 in as the serial port the printer connects and works great. my problem is i need to be able to log in to multiple pages at one and use the different usb ports dedicated to this. problem is on the octoprint web page where it says to add a serial port when i put it in the box and hit save. all i get in the drop down menu is the choose of usb0 and auto. how/why wont it list the new serial port i entered, and if im doing it wrong how do i make it so each webpage:port uses a different serial port

**Comment by guysoft** [comment]
If that computer isn't a raspberrypi or a device running armbian then this
is an OctoPrint issue and not an OctoPi issue. Please use OctoPrint's issue
tracker at:
https://github.com/foosel/OctoPrint/issues
