### ISSUE TITLE
Octopi 0.13 boot issue - New Rpi3

### ISSUE THREAD

**Issue by martinold** [guysoft/OctoPi#368]
Imaged is flashed to a sd card and inserted in to RPi3. Boot freezes at line
4.189155] ---[ end kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(179,2)
.img downloaded from https://octopi.octoprint.org/

Possible cause please?

![19237786_1568784613194532_3740433830364288187_o](https://user-images.githubusercontent.com/29520947/27261558-65dd4480-543d-11e7-8a07-bd6e88b8f82d.jpg)

**Comment by guysoft** [comment]
Are you sure its flashed correctly? Its likely an io error or something
like that.

**Comment by martinold** [comment]
I downloaded. Extracted to desktop, burned image to sd using win32diskImager, also retried with Etcher directly from .zip file, uncommented and edited SSID/password, ejected card and put into pi and then powered up. I have also tried 2 different card types, the better one being a SanDisk 32gb hc1.

**Comment by guysoft** [comment]
Its basically going over the frequent errors at this point:
What power supply and CABLE are you using? Does the top right of the screen show a colored box?
Are you plugging any USB devices in?

**Comment by martinold** [comment]
Power supply 2.4 A, also tried a spare 2 A. Unsure of cable but tried some thick looking ones I have.
Coloured box appears and then fades when boot stops. Also 4 rasberry icons at top of screen.
I have tried booting with and without USB devices, keyboard, mouse, logitech cam.

**Comment by martinold** [comment]
I have noticed .bin file has an association with notepad. Is this important?

**Comment by guysoft** [comment]
Whichv.bin file?
Have you tried reflashing?

**Comment by martinold** [comment]
The boot code .bin has an association. 
Yes to reflashing but association stays.
![20170618_182253](https://user-images.githubusercontent.com/29520947/27262689-eac07aa8-5453-11e7-9fb2-eb400517c2ea.jpg)

**Comment by martinold** [comment]
I think all is well now. Flashed drive on a different computer, same card, same procedure but boots fine now. I am mystified but happy it boots.
