### ISSUE TITLE
Wrong download...

### ISSUE THREAD

**Issue by bilbat** [guysoft/OctoPi#375]
I would be glad to help along with this beta, but when I click on the download link, instead of the listed modded file, I get a straight 14.0 download - no .1.3 at all!

**Comment by John-Mc** [comment]
The straight 0.14 download does not exist yet. You have the correct file.

**Comment by guysoft** [comment]
0.14 is planned to be released tomorrow, and unless something is reported
today it will be RC3.

**Comment by guysoft** [comment]
Released
