### ISSUE TITLE
Accessing Snapshot inside IOS App

### ISSUE THREAD

**Issue by rgruskin** [guysoft/OctoPi#376]
I would like to write an IOS app (in swift) to access the most recent snapshot from OctoPi and display it in my app.  Not sure the best way to approach this.  Eventual goal is to have my App running on iWatch and quickly seeing latest snapshot.  Any suggestions?

**Comment by Penfold81** [comment]
Octoprint does this already? I use the app on my watch?

Sent from my iPhone

On 2 Jul 2017, at 21:22, rgruskin <notifications@github.com<mailto:notifications@github.com>> wrote:


I would like to write an IOS app (in swift) to access the most recent snapshot from OctoPi and display it in my app. Not sure the best way to approach this. Eventual goal is to have my App running on iWatch and quickly seeing latest snapshot. Any suggestions?

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi issue, please use the OctoPrint issue tracker or mail list:
https://github.com/foosel/OctoPrint/issues/
https://groups.google.com/forum/#!forum/octoprint
