### ISSUE TITLE
Input field for Target hotend temperature only displays one character

### ISSUE THREAD

**Issue by OutsourcedGuru** [guysoft/OctoPi#378]
The input control associated with Target can't display more than a single digit/character.  Upon startup, that control is trying to display "off" but it can only manage to show the first letter of that.

If you attempt to enter "123" you can only see the last digit typed.

![screen shot 2017-07-09 at 4 04 01 pm](https://user-images.githubusercontent.com/15971213/27999475-63814772-64d2-11e7-9dee-ef283993908e.png)

In Safari, I attempted to go into the Inspect Element screen.  In this screen you can edit the style, for example, to see the result.  I attempted to change "input-mini" to "input-small"/"input-medium"/"input-large" but this did not change the appearance.  If you delete the "tempInput" class then it will size differently, actually seeing the sizing distinction.  It looks like that tempInput style is unnecessarily overriding the other, forcing it to something like 50x34 pixels.

```
<input type="number" class="input-mini text-right tempInput" data-bind="attr: {placeholder: cleanTemperature(target()) }, value: newTarget, enable: $root.isOperational() &amp;&amp; $root.loginState.isUser(), event: { keyup: function(d, e) {$root.handleEnter(e, 'target', $data);} }" placeholder="off">
```

Within the source, the file in question appears to be `~/OctoPrint/src/octoprint/templates/tabs/temperature.jinja2` and it's down around line 26.

Browser: Safari 10.1

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to
https://github.com/foosel/OctoPrint/issues/
