### ISSUE TITLE
Problem with free space

### ISSUE THREAD

**Issue by leobel96** [guysoft/OctoPi#380]
Hello, I installed Octopi on a 2gb micro sd some weeks ago and everything worked like a charm. Today I decided to transfer everything on a larger micro sd card (8 gb) because of I thought that, after updates and new plugins, 400 free mbyte are too little. I used [this](https://raspberrypibeginner.wordpress.com/2013/03/25/moving-the-pis-system-to-a-larger-sdcard/) guide and everything seemed to be ok. I switched on raspberry with the new sd card and everything was ok, I expanded the file system and, then, I rebooted but, after the login in the OctoPrintUI I noted that the free space in sdcard remained 462mb. How is it possible? I attach the screenshoot. Thank you and congratulation for you work!!
![cattura](https://user-images.githubusercontent.com/19806799/28072086-26f68b56-6652-11e7-81a4-4d1e462d9972.PNG)

**Comment by guysoft** [comment]
What do you get if you run ``df -h`` in the commandline of the raspberrypi?

**Comment by leobel96** [comment]
Thank you for your reply. With the new sdcard I obtain this (http://imgur.com/a/P73ai)

**Comment by guysoft** [comment]
Ok, first it looks like it did expand the system.
1. Did you reboot?
2. @fossel is there a known issue?

**Comment by leobel96** [comment]
Yes, I rebooted 5 times. I didn't know if post the issue here or on octoprint because is something on the borderline.

**Comment by Salandora** [comment]
Can you try a Shift+F5 reload on your browser, it could be a caching problem maybe.

**Comment by leobel96** [comment]
@Salandora I love you. I deleted the cache from Firefox settings and now free space is 5.6GB. Thank you so much!!!
