### ISSUE TITLE
After Abort of a print job the nozzle heater is switched off in the next job

### ISSUE THREAD

**Issue by Pixopaxo** [guysoft/OctoPi#381]
Example:

I load a job, start the print
Then I abort the job

I load a new job
Start it
It heats up the bed and nozzle, then after reaching the temperature it starts the print
Then suddenly it switches off the nozzle heater, but runs the job further, no material is coming out because of the cold nozzle.

I always need to switch off octo and restart to run a job after I aborted one.

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
