### ISSUE TITLE
Wrong Path in Sudoers File

### ISSUE THREAD

**Issue by Sunoo** [guysoft/OctoPi#387]
In OctoPi, the sudoers file /etc/sudoers.d/octoprint-service has the wrong path to the 'service' command. It lists it as /sbin/service, but the correct path is /usr/sbin/service.

**Comment by guysoft** [comment]
@foosel 
Looks like he is right:
```
root@octopi:/home/pi# which service
/usr/sbin/service
```
.
Its added here:
https://github.com/guysoft/OctoPi/blob/devel/src/modules/octopi/start_chroot_script#L136

Fixing

**Comment by foosel** [comment]
I know, I already stated that in #345, but it doesn't matter as long as OctoPi sticks to that "let's just never ask a password from the user for sudo anyway" approach that Raspbian ships with by default.

**Comment by guysoft** [comment]
Oh hell, your solution is better.
I think we can try it in devel after CustomPiOS merge becomes stable
