### ISSUE TITLE
Can't build Octopi with Raspian Jessie

### ISSUE THREAD

**Issue by scottmil** [guysoft/OctoPi#389]
I tried to build Octopi using the scripts provided in the README.rst file, and the final sudo bash ./build_dist fails with a message that it cannot find the Variant. I checked all the pi directories, and the contents seem correct.  There is also a config file in /home/pi/OctoPi/src which I assume is the default Variant.

/home/pi/CustomPiOS/src /home/pi/OctoPi/src
+++ git rev-parse HEAD
++ export OCTOPI_COMMIT=c9db4cd79bd2f1a1a649b85e66c2ec49b035691e
++ OCTOPI_COMMIT=c9db4cd79bd2f1a1a649b85e66c2ec49b035691e
++ popd
/home/pi/OctoPi/src
++ BUILD_VARIANT=default
++ BUILD_FLAVOR=default
++ WORKSPACE_POSTFIX=
++ '[' 1 -gt 0 ']'
++ BUILD_VARIANT=/home/pi/OctoPi/src
++ '[' 1 -gt 1 ']'
++ '[' /home/pi/OctoPi/src '!=' default ']'
++ WORKSPACE_POSTFIX=-/home/pi/OctoPi/src
++ '[' -d /home/pi/OctoPi/src/variants//home/pi/OctoPi/src ']'
++ '[' -d /home/pi/CustomPiOS/src/variants//home/pi/OctoPi/src ']'
++ die 'Could not find Variant /home/pi/OctoPi/src'
++ echo 'Could not find Variant /home/pi/OctoPi/src'
Could not find Variant /home/pi/OctoPi/src
++ exit 1
+ exit 1
+ exit_code=1
+ '[' 1 -ne 0 ']'
+ exit 1

**Comment by guysoft** [comment]
Fixed, indeed there was a bug, pull from OctoPi devel and it should work
