### ISSUE TITLE
competition. 

### ISSUE THREAD

**Issue by rewolff** [guysoft/OctoPi#399]
http://www.gocomics.com/theargylesweater/2017/08/12

**Comment by guysoft** [comment]
Can't reproduce.
Maybe this workaround might work: https://www.thingiverse.com/thing:10337

**Comment by guysoft** [comment]
![fb_img_1519298160967](https://user-images.githubusercontent.com/325670/36630412-96509df0-196e-11e8-8498-47c35b5214d5.jpg)

**Comment by guysoft** [comment]
No one is funny anymore, closing.
