### ISSUE TITLE
Include upgrade script for OctoPrint

### ISSUE THREAD

**Issue by guysoft** [guysoft/OctoPi#4]
I have been thinking for a while to include a script that will let you upgrade to the latest and greatest OctoPrint, and would also include rollback support.
I have a feeling other people have already things they use, so please feel free to share your snippets so we can get the best result.

Meanwhile you can update manually using:

    cd ~/OctoPrint ; git pull origin ; ~/oprint/bin/pip install -r ~/OctoPrint/requirements.txt

**Comment by guysoft** [comment]
Is this still in TODO?:
https://github.com/OctoPrint/OctoPrint-SoftwareUpdate

**Comment by seefood** [comment]
Hey guys, so is there a way to update my OctoPi other than the pip install upgrade of the OctoPrint itself?

If I need to get the entire image again and overwrite my image, what's the list of files I want to back up so I don't have to create new logins and API keys for Cura?

Worth adding to the readme, I think...

**Comment by guysoft** [comment]
Not really.

I tried once writing a backup script, if you want you can write an analogue "restore" that should do the trick:

```bash
#!/bin/bash
OS_PATH=/media/path/to/sd/card
DEST_PATH=/tmp/sdcard

rm -rf ${DEST_PATH}
mkdir -p ${DEST_PATH}

backup(){
    mkdir -p ${DEST_PATH}$1
    cp -av ${OS_PATH}$1 ${DEST_PATH}$1
}

backup /home/pi/.octoprint
backup /home/pi/OctoPiPanel/OctoPiPanel.cfg
backup /etc/network/interfaces

GLOBIGNORE=".:.."
shopt -u dotglob

pushd ${DEST_PATH}
    tar czvf backup.tar.gz  * 
````

**Comment by foosel** [comment]
Can be closed now that OctoPrint ships with integrated update mechanism and OctoPi 0.12 will have that configured out of the box.

Reopen if you disagree :)

**Comment by seefood** [comment]
Upgrading the OctoPrint means all the rest of the plugins and components of OctoPi are upgraded too? like the mjpeg streamer and other bits? or do those get upgraded with an apt-get upgrade?
