### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by brettlg** [guysoft/OctoPi#401]
Is is possible to have multiple watched folders with 1 slicing profile assigned to 1 watched folder.  i.e. watched folder "ABS 0.1mm" with a corresponding slicer profile, watched folder "PLA 0.4mm" with corresponding slicer profile.  Goal different folders different profiles applied, simple drag and drop to appropriate folder for processing.  Hope this is the correct place to post.

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
