### ISSUE TITLE
Debian Stretch

### ISSUE THREAD

**Issue by dylanmtaylor** [guysoft/OctoPi#402]
What are the plans, moving forward, to base the OctoPi image off of Raspbian Stretch? This is the new stable release, and it would be nice to be on the latest codebase. I see a commit was made 2 days ago to add Stretch into nightlies, but the latest 0.14 build is still Jessie.

**Comment by guysoft** [comment]
There is a working nightly.  Try it out

**Comment by dylanmtaylor** [comment]
Mine does not start. I couldn't ssh into pi@octopi.local, so I plugged in a monitor. Looks like there is an issue starting the HAProxy load balancer service

**Comment by dylanmtaylor** [comment]
![image](https://user-images.githubusercontent.com/277927/29497871-4f31334c-85be-11e7-9359-eac626a3f015.png)

**Comment by dylanmtaylor** [comment]
This is on a Raspberry Pi Zero W. The SD card is an 8GB Sandisk and the USB port has a powered hub with an Original Prusa MK2S and a Logitech V-UBM46 USB Webcam plugged in. This is the 0.15 nightly image from last night. 

![image](https://user-images.githubusercontent.com/277927/29497904-e1da70c8-85be-11e7-8e24-aadf7f6235bb.png)

**Comment by guysoft** [comment]
@foosel When you are back from vacation, not sure I'll have time to find why this fails before I fly out )'( .

**Comment by ntoff** [comment]
`2017-08-16-octopi-stretch-lite-0.15.img` won't connect to the wifi for me (and I also get that haproxy message).

    pi@octopi:~ $ sudo ifdown wlan0
    ifdown: interface wlan0 not configured
    pi@octopi:~ $ sudo ifup wlan0
    wpa_supplicant: /sbin/wpa_supplicant daemon failed to start
    run-parts: /etc/network/if-pre-up.d/wpasupplicant exited with return code 1
    ifup: failed to bring up wlan0-octopi
    pi@octopi:~ $


haproxy log https://gist.github.com/ntoff/3d41f1b818d7c9fcaa52e8836d7a116e

**Comment by guysoft** [comment]
Wifi works for me, but also saw users on reddit complaining about stuff: https://www.reddit.com/r/raspberry_pi/comments/6ugenm/stretch_and_headless_setup_zero_w/

**Comment by ntoff** [comment]
This is on a raspberry pi 3 btw, forgot about that part.

**Comment by guysoft** [comment]
``octopi-wpa-supplicant.txt`` is the way to go. We kept the old one for backwards compatibility. Might remove it in later versions.

Thanks for the update about ``bind :::443 v4v6 ssl crt /etc/ssl/snakeoil.pem``. It probably means the certificate is not being generated.

**Comment by ntoff** [comment]
It's not, nor is the octoprint service being started or webcamd, at least not on the images I tried to build using the build instructions.

Commenting out the line in the chroot script that attempts to disable lightdm (I think it was around 179, sysctl_if_exists lightdm disable) fixes the webcam and octoprint services not being installed (don't ask me how or why *that* works) but gencert still never runs on boot BUT it can be run manually after logging in.

**Comment by guysoft** [comment]
Managed to test a bit in between. There is an issue in policykit. Its complaining about permissions.
(Writing this from a tent in the middle of the desert. So will try fix around Sunday).

**Comment by guysoft** [comment]
Ok, seems like the issue is solved when installing policykit-1, testing here and should be out in the next nightly.
