### ISSUE TITLE
OctoPi Webcam not working

### ISSUE THREAD

**Issue by Shad0wK1ng2003** [guysoft/OctoPi#403]
I can tell that the actual webcam server itself, mjpg-streamer, if functioning because I am able to access http://octopi.local/webcam/?action=stream, however, once I actually get there, all I am able to see is this:
![octoprint camera](https://user-images.githubusercontent.com/10590042/29647177-e6601d34-8855-11e7-94ad-e3137f83c54e.jpeg)

I'm using a relatively popular webcam, I forget whether it's a Logitech c310 or c210, but I should work, right?

**Comment by guysoft** [comment]
Please see https://github.com/foosel/OctoPrint/wiki/Webcams-known-to-work , there is a spesific usb option for the c310. Also there are users who reported it working.
