### ISSUE TITLE
Start offset parameter

### ISSUE THREAD

**Issue by johnryanlee** [guysoft/OctoPi#415]
Printer: Geeetech Prusa I3 W
Board: GT2560
Firmware: Marlin 1.1.5

My printer's home position is X-20 Y0 Z0
I haven't tested yet but it appears that I need to set the X_MIN_POS in Marlin firmware to -20 to manage the offset.

It would be great if Octoprint would be able to take a parameter to handle the offset

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
