### ISSUE TITLE
[Not issue] what the best way to read current gcode from shell?

### ISSUE THREAD

**Issue by EnricoSx** [guysoft/OctoPi#422]
what the best way to read current gcode **from shell**?

example, i want create script bash or python to monitor when printer, during print from sd, use some gcode, example.
EXAMPLE: when, during print from sd, use G1 Z5 , send email 
thanks

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/

I'd look in to OctoPrints's API
