### ISSUE TITLE
Raspbian Stretch - How stable?

### ISSUE THREAD

**Issue by pthieu** [guysoft/OctoPi#439]
This might not be the best place to ask, but Reddit activity is quite low and I can't find any other forum with information.

Noticed there's quite a bit of development for Raspbian Stretch. Is there a page that shows a summary of known issues or the stability for the newest builds?

Should we add a page in the wiki or directly to the README.md for this type of information if it doesn't exist already?

**Comment by Grogyan** [comment]
Better question is, is Stretch stable enough to enable OctoPI to use it as the base OS over Jessie?

**Comment by guysoft** [comment]
Closing if no reply, Stretch seems pretty solid.
