### ISSUE TITLE
File upload dates inaccurate

### ISSUE THREAD

**Issue by ChristiaanDev** [guysoft/OctoPi#443]
I use the RestAPI in order to upload files to the OctoPi. However when i upload something it says it was uploaded way earlier than i actually uploaded it (Example, uploaded it 1 minute ago, shows up as 5 days ago), clearly not correct. It's not an huge issue, but would be nice if it'd get fixed.
Thanks

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
