### ISSUE TITLE
Strange signs from my printer while connecting since 1.3.5

### ISSUE THREAD

**Issue by dansche** [guysoft/OctoPi#445]
Hi Community

Since i upgraded to 1.3.5 i can‘t connect to my printer anymore, seems Octoprint is running correctly, before the upgrade i was connected in seconds after i pushed connect.

Now if I push connect, Octopi establishes a connection and is receiving strange letters an signs as black question marks and other things.

![01abf3e8-7c27-4c4b-b803-89c8c950fa44](https://user-images.githubusercontent.com/18419980/33513992-33316f2e-d74c-11e7-9b82-0dd6f820a539.jpeg)

Anyone else experience that? How can I solve that? As said with the old version it was running perfectly.

Thanks for your help.

Dansche

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
