### ISSUE TITLE
com to 2 devices for filament splicer

### ISSUE THREAD

**Issue by dwc56** [guysoft/OctoPi#453]
is the a way to have octopi have the normal communication with the printer but also have a communication with another device like a arduino nano over usb or gpio uart that would clone the communication with the printer i am trying to make a filament splicer for multicolored printing and it needt to see the printer current position i tried making a plugin but i could not get it to work so if anyone knows how to do the please tel me

**Comment by guysoft** [comment]
This is more of an OctoPrint issue,  not an OctoPi issue

**Comment by guysoft** [comment]
Closing if no reply
