### ISSUE TITLE
incorrect IP address in octopi-network.txt

### ISSUE THREAD

**Issue by HassanKanj** [guysoft/OctoPi#455]
Hello,

in octopi-network.txt (L.54), it should be 192.168.250.1 instead of 192.168.250.10 to match with L.60

**Comment by guysoft** [comment]
1. You are welcome to pull request with an explanation
2. What is L.54 and L.60 ? I can't find anything when I Google for it. .1 tends to be the gateway and not the IP of OctoPi

**Comment by John-Mc** [comment]
“line 54” and “line 60”?  I don’t have the files handy to see if that makes
sense.

**Comment by guysoft** [comment]
Filles are [here in the network module](https://github.com/guysoft/CustomPiOS/blob/CustomPiOS/src/modules/network/filesystem/boot/custompios-network.txt)

**Comment by guysoft** [comment]
Line 54: https://github.com/guysoft/CustomPiOS/blob/CustomPiOS/src/modules/network/filesystem/boot/custompios-network.txt#L54

**Comment by nallar** [comment]
They're supposed to be different. Line 54 is the configuration to use on a PC. Line 60 is for octoprint.

If you set two systems with the same static IP they won't be able to talk to each other.

**Comment by guysoft** [comment]
Yep, ok, closing
