### ISSUE TITLE
Raspberry PI3 and 7" LCD Touch screen not powering up

### ISSUE THREAD

**Issue by Joaeil** [guysoft/OctoPi#456]
I have a setup involving a CraftBeer PI card mounted on a Raspberry PI3 card and a Raspberry 7" LCD Touch screen.
I´m trying to use 2 power sources, because one is not sufficient to run the whole setup.

The Craftbeer PI card requires 12V/5A and it has an adjustable stepdown "buck" that is set to deliver 5.1V to the Raspberry PI below. The CbPi card/RbPI is powered via a MDR-60-12 transformator (see pictures).
The screen is attempted powered via another MDR giving 5V/3A.
However, the system/screen is not powering up/booting.
Does anyone have an idea of what I´m doing wrong here?

PS! I have measured Volts & Amps using a multimeter.

![img_0974](https://user-images.githubusercontent.com/33182921/34516370-f42a1af8-f076-11e7-8461-81c540fadc5e.JPG)
![img_1025](https://user-images.githubusercontent.com/33182921/34516909-1bc7b406-f079-11e7-8c21-e0535e19ab20.JPG)
![img_0910](https://user-images.githubusercontent.com/33182921/34517107-f750fb72-f079-11e7-9254-71377207f5a1.JPG)
![img_0912](https://user-images.githubusercontent.com/33182921/34517160-2a48a052-f07a-11e7-846c-4d915e7cbfc2.JPG)

Regards
Joachim Eilers

**Comment by John-Mc** [comment]
I will defer to Guy here, but since this is not related to OctoPi, I might suggest posting in one of the Raspberry Pi forums such as www.raspberrypi.org/forums/

**Comment by guysoft** [comment]
Or CraftBeerPiOS issue tracker: https://github.com/guysoft/CraftBeerPiOS

OctoPi is a distribution running OctoPrint to control 3D printers which I am also developing. Not connected to Craftbeerpi

**Comment by Joaeil** [comment]
Thank you for input @John-Mc and @guysoft !
