### ISSUE TITLE
Extruder drops from 210 to 195 when printing (PLA)

### ISSUE THREAD

**Issue by Martyfree123** [guysoft/OctoPi#457]
Ive noticed that when i head my TAZ 5 to 210 and then start printing, Octoprint automatically drops the temp to 195...

**Comment by John-Mc** [comment]
Are you slicing on the Pi, or on another computer? Wherever you are slicing, I'd look at the slicing profile you are using. If it is set for 195, it may override whatever you set via OctoPi's temperature tab

**Comment by Martyfree123** [comment]
I'm slicing on my MBP with Cura. I did recently change to a different version of Cura so I'm sure that's the culprit. Thank you so much! I wouldn't have thought of that!

**Comment by John-Mc** [comment]
BTW, @Martyfree123, there is an OctoPrint users group on FaceBook where you can also go for help: [OctoPrint Users Group](https://www.facebook.com/groups/piprint/)

**Comment by Martyfree123** [comment]
Awesome! :)
