### ISSUE TITLE
Time bug

### ISSUE THREAD

**Issue by Zamundaaa** [guysoft/OctoPi#459]
It seems as though the PI wouldn't update its system time anymore. It is a minor inconvenience as in the browser it shows the wrong upload times of files. If I upload something it shows me "uploaded 22 days ago". The rest works as normal
How can I fix it (other than updating the time manually)?

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
