### ISSUE TITLE
No documentation on how to enable rpi-display and adafruit-pitft and get OctoPiPanel to work on boot

### ISSUE THREAD

**Issue by guysoft** [guysoft/OctoPi#46]
Pushed to devel the new OctoPiPanel and scripts to configure it with rpi-display and adafruit-pitft scripts that are located in `/home/pi/scripts/enable-rpi-display` and `/home/pi/scripts/enable-adafruit-pitft`. For now it seems best to go on README.rst in the "How to use it?" section.

**Comment by korneelb** [comment]
Hi;
wanted to let you know I did not have any luck.
my setup : Raspberry PI B+ with camera module and an Adafruit PITFT.
what i did:
setup Ubuntu and build the latest version of Octopi as per your guide (your guide misses installing prerequisites "zip" and "git" BTW..) .
flash the image to my SD card
switched the branch of OctoPi to devel by using git checkout devel
reran the installer of OctoPi to make sure i was using the latest bits

went into the scripts directory and ran ./enable-adafruit-pitft
rebooted
went into the scripts directory and ran calibrate-rpi display

this all went succesfull.

got the API key from the Octoprint interface, and put this in the octopipanel.cfg file
rebooted
ran the sudo python ./OctoPiPanel.py & in the OctoPiPanel directory.
screen shows OctoPiPanel for a few seconds, no values in temp, then dies with the following error in my terminal:


pi@octopi ~/OctoPiPanel $ OctoPiPanel initiated
OctoPiPanel started!
---
Traceback (most recent call last):
  File "./OctoPiPanel.py", line 612, in <module>
    opp.Start()
  File "./OctoPiPanel.py", line 206, in Start
    self.get_state()
  File "./OctoPiPanel.py", line 309, in get_state
    self.HotEndTemp = state['temps']['tool0']['actual']
KeyError: 'temps'
^C
[1]+  Exit 1                  sudo python ./OctoPiPanel.py

**Comment by jonaslorander** [comment]
@korneelb, are you using the dec branch of OctoPrint? OctoPiPanem is not yet up to match the dev branch. The API has changed between latest release and dev.

**Comment by korneelb** [comment]
Hi Jonas;

I assume you mean the devel branch, yes I am using that.. 
so this is a bummer.. ok so no OctoPiPanel for me then :/

**Comment by jonaslorander** [comment]
Yeah, I mean devel.
My intent is for the devel-branch of OctoPiPanel to follow the devel-branch of OctoPrint. But I haven't come around to it yet. You could follow OctoPiPanel for updates.

**Comment by korneelb** [comment]
ok, i will. what is the best place to follow this?
also, it seems that the screen initializes, it shows me OctoPiPanel, but then shuts down after a couple of seconds going back to a black screen. is that known behaviour?

**Comment by guysoft** [comment]
@korneelb Just making sure you know - Have you tried using the official OctoPi release? The first step would be to make sure you can get the screen running from there.

**Comment by jonaslorander** [comment]
@korneelb, that is a known behavior. It's a screen saver and can be turned off in the config file for OctoPiPanel. You can follow OctoPiPanel here: https://github.com/jonaslorander/OctoPiPanel

**Comment by korneelb** [comment]
Hi Guysoft;

Yes i tried the official 10.1 and 10.0 with OctoPiPanel releases. problem appears to be that i switched to the devel branch of Octoprint. the Master Branch does not ahve the change in it that forces the nozzle to wait for a while until the bed is heated... 

I've tried the screen and that is working.

@jonaslorander  I turned the screensaver off.. no change..

**Comment by jonaslorander** [comment]
If you are using the devel it crashes because if changed API. Should not blank the screen though.

**Comment by korneelb** [comment]
so here's the fun part.. it does ;)

this is my config file:


[settings]
baseurl = http://localhost:5000
apikey = 91FB5133657743EBA2ANDTHERESTOFMYAPIKEY

updatetime = 2000
backlightofftime = 0

window_width = 320
window_height = 240


when i try to run it using  sudo python ./OctoPiPanel.py &  
it  initializes my PiTFT, it shows the OctoPiPanel interface, all values zeroed, then i get a terminal error as above (which is logical i suppose due to me being on devel) then the screen blacks out again.

**Comment by guysoft** [comment]
OctoPiPanel is legacy, closing
