### ISSUE TITLE
Novice at best.  How do I load plugins on my octopi?  Can it run a browser?

### ISSUE THREAD

**Issue by ThatNet** [guysoft/OctoPi#461]
I appreciate your help.

If this is all covered somewhere already please point me there.  

Google hasn't been very effective for me on this one.

Cheers.

**Comment by guysoft** [comment]
1. You are mixing between OctoPrint and OctoPi, google for that
2. OctoPi has a desktop install script to install a desktop and a browser.
3. Google for OctoPrint plugins, there are several guides

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
