### ISSUE TITLE
prusa i3 MK2 stops printing

### ISSUE THREAD

**Issue by dagobertch** [guysoft/OctoPi#463]
I had a issue, that sometime the print stops during print, the hotend and bed keep heating and octopi is not reachable anymore.
Today I found maybe why:
A print stops and a few mintes after this stop, octopi was reacheable, so I took a look into the Terminal:

Send: N21377 G1 X164.158 Y115.656 E0.15215*111
Recv: ok
Send: N21378 G1 X168.339 Y114.536 E0.10151*107
Recv: Error:checksum mismatch, Last Line: 21376
Recv: Resend: 21377
Recv: Error:Line Number is not Last Line Number+1, Last Line: 21376
Recv: Resend: 21377
Communication timeout during an active resend, resending same line again to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Send: N21376 G1 X164.158 Y109.168 E0.10151*111
Recv: Error:Line Number is not Last Line Number+1, Last Line: 21376
Recv: Resend: 21377
Communication timeout during an active resend, resending same line again to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
Send: N21376 G1 X164.158 Y109.168 E0.10151*111
...

Looks like the printer wants to get the line N21377 again and octopi resends only N21376

Is this an octopi issue or a printer issue or both?

**Comment by guysoft** [comment]
Neither, this is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/

Also you might want to change the timeout settings.
