### ISSUE TITLE
plugin mannager wont download plugins  

### ISSUE THREAD

**Issue by effysh** [guysoft/OctoPi#467]
hi i am unable to download plugins from the repo as a link in the octoprint console 
i get this error :  
by the way when i download the zip its ok

Installing plugin from https://github.com/cesarvandevelde/OctoPrint-M73Progress/archive/master.zip".../home/pi/oprint/bin/python -m pip install 'https://github.com/cesarvandevelde/OctoPrint-M73Progress/archive/master.zip"'Invalid requirement: ''https://github.com/cesarvandevelde/OctoPrint-M73Progress/archive/master.zip"''It looks like a path. Does it exist ?Error!Could not parse output from pip, see plugin_pluginmanager_console.log for generated output

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
