### ISSUE TITLE
ReadMe references src/variants/example which does not exist

### ISSUE THREAD

**Issue by xxbiohazrdxx** [guysoft/OctoPi#469]
Trying to build a armbian variant, since it looks like it is supported based on #426 #419 #232 but the readme/wiki seems really incomplete. Specifically, the readme mentions building w/ variants but the examples directory does not exist.

**Comment by ntoff** [comment]
I think some bits were moved over to the custompios part, variants is over there now (custom pi os is listed as one of the requirements, did you also download that?)
https://github.com/guysoft/CustomPiOS/tree/CustomPiOS/src/variants

**Comment by guysoft** [comment]
armbian variant moved to the CustomPiOS project, its maintained there.
