### ISSUE TITLE
Add static IP on wlan0 example to /boot/octopi-network.txt

### ISSUE THREAD

**Issue by b-morgan** [guysoft/OctoPi#470]
Most of the pages I've found on the internet suggest editing /etc/dhcpcd.conf to add static IP addresses to eth0 and wlan0. OctoPi has example lines for setting a static IP address on eth0 in /boot/octopi-network.txt but none for a static IP address on wlan0. I believe /boot/octopi-network.txt would be a better place to add these lines for all the reasons that it exists in the first place.

**Comment by guysoft** [comment]
Its not the same configuration file, they are parsed differently, they are from different software packages.
dhcpcd.conf is from dhcpcd5.
``/etc/network/interfaces`` is part of Debian. Closing, its not something I can change in the scope of OctoPi.
