### ISSUE TITLE
Little Problem with Display window.

### ISSUE THREAD

**Issue by interceptor70** [guysoft/OctoPi#471]
![slicing](https://user-images.githubusercontent.com/35465613/35769798-fd635e88-0910-11e8-8251-8d5540a35e9e.jpg)
Please help me to fix it :)

![slicing](https://user-images.githubusercontent.com/35465613/35769785-c8e8f9ce-0910-11e8-9b2e-9fc2ae31e81d.jpg)

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
