### ISSUE TITLE
no longer to get to webcam settings at http://printer:8080/control.htm

### ISSUE THREAD

**Issue by ch0de** [guysoft/OctoPi#478]
I reloaded my Octopi few days ago and i am not longer able to get to http://printer:8080/control.htm. 

when i go there it is a page that just give a image and a video steam, the old page that looked like this https://imgur.com/a/zO6Hp     is gone

**Comment by guysoft** [comment]
I have no idea. Please provide logs. But it sounds like a localized error.

**Comment by ch0de** [comment]
[octoprint.log.2018-02-13.txt](https://github.com/guysoft/OctoPi/files/1725574/octoprint.log.2018-02-13.txt)

**Comment by ch0de** [comment]
https://imgur.com/a/zO6Hp

Is that the webpage i should still get when i goto  http://printer:8080/

If so maybe i will reload again.

**Comment by guysoft** [comment]
Wait, when you say "reloaded", you mean flashed a new image?
Did you flash a newer version? It might be that the HAPRoxy parameters have changed.

**Comment by ch0de** [comment]
Yes I flashed the new image from GitHub.

**Comment by ch0de** [comment]
![capture](https://user-images.githubusercontent.com/28579984/36499896-3dd83722-1708-11e8-9fd4-fecfac57f3b2.JPG)
here is what the screen looks like after i flashed new image..

**Comment by guysoft** [comment]
This ks expected behavior due to security reasons as stated inhttps://github.com/guysoft/OctoPi/pull/359

**Comment by ch0de** [comment]
I understand this is now excpected behave after reviewing your other post. However how do i get that back? i only see a discription for the -N option. 

I need that camera page to disable auto focus and set the focus range.

**Comment by guysoft** [comment]
The information is here.
I am really not supporting this:
https://github.com/jacksonliam/mjpg-streamer/tree/master/mjpg-streamer-experimental/plugins/input_uvc

To do what you want you need to reverse what Gina discribes. aka switch here the webroot from www-octopi back to www:
https://github.com/guysoft/OctoPi/pull/359/files#diff-90ef84c6aacfc0fe4a6a5655ff158526R22
