### ISSUE TITLE
Adding a webcam to the default ones that do not support the -f parameter

### ISSUE THREAD

**Issue by Zvax** [guysoft/OctoPi#480]
Hey there. I think that the webcam integration is in OctoPi's area? At some point in `/boot/octopi.txt` it's written:

```
# If this fixes your problem, please report it back so we can include the device
# out of the box.
```

So here I am, reporting that adding 

`additional_brokenfps_usb_devices=("046d:082b" "1e4e:0102")`

Fixed my webcam. Some of [these](https://github.com/guysoft/OctoPi/issues/365) people seem to have the same 1e4e prefix to that same configuration. Maybe all 1e4e devices are faulty? Is there a way to have a wildcard of sort on that vendor?

I'm open to doing it and opening a PR if given some general direction.

Cheers!

**Comment by guysoft** [comment]
I don't understand - you are reporting that using the OctoPi configuration provided solved your problem? That is why its there.
Of is there something else you wanted to say that I missed?
