### ISSUE TITLE
Checking printing status with python script?

### ISSUE THREAD

**Issue by Synthron** [guysoft/OctoPi#497]
Hey,

I wanna read out the printing status (in percent) of Octoprint with Python to control a PWM-GPIO for driving a selfmade VU-meter for visualizing the status as a visual indicator. How can I get the status?

best regards

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
