### ISSUE TITLE
Nightly builds place css seems to be broken

### ISSUE THREAD

**Issue by guysoft** [guysoft/OctoPi#500]
So would love help @foosel when you have time.
Tried fixing with this commit: https://github.com/guysoft/OctoPi/commit/1c2f620f3d1253752a78f9a8e601b1face88fdbc
The faviocn started working but the CSS seems to be broken still.

**Comment by foosel** [comment]
https://github.com/guysoft/OctoPi/commit/cab49af08fa69061d9a4dc1df001821719296abd#diff-efadc9de25fac213265eacbd941b4048

**Comment by guysoft** [comment]
Tested, fixed
