### ISSUE TITLE
outgoing ssh trouble

### ISSUE THREAD

**Issue by Kalle3D** [guysoft/OctoPi#501]
i had trouble with outgoing ssh connections from octopi.
the connection to most servers was very unstable, was hanging etc.

the problem is similar to https://github.com/guysoft/OctoPi/issues/294, but here in outgoing direction.
the problem can be fixed by 

adding the line
IPQoS 0x00
to the file
/etc/ssh/ssh_config

also. until now this was only corrected in the file /etc/ssh/sshd_config, which is the config  for incoming connections to the local octopi sshd.
but the outgoing ssh connection should be set to IPQoS 0x00 also.
i added it as last line in /etc/ssh/ssh_config and it works.

**Comment by guysoft** [comment]
Hums, 
I am going to fix this and also move it up to CustomPiOS
