### ISSUE TITLE
issues with Raspi B+

### ISSUE THREAD

**Issue by mtowara** [guysoft/OctoPi#509]
Hi,
just a heads up,
I'm seeing crashes with my brand new Raspi B+,
which leads to the print failing midway and the pi not responding at all.

This seems to be hardware/kernel related and nothing to do with OctoPi/Print.
I'm using the official 2.5A power brick, thus I'm somewhat confident that its not an power issue.

My best guess is that it is this issue:
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=208821

**Comment by guysoft** [comment]
I guess this blocks #505 , thanks for reporting

**Comment by guysoft** [comment]
There is a new image that I think fixes all this stuff. Please see #516 , if there is no news I will close this.

**Comment by guysoft** [comment]
Released https://github.com/guysoft/OctoPi/releases/tag/0.15.0
