### ISSUE TITLE
add wiringpi...?!

### ISSUE THREAD

**Issue by rooiejoris** [guysoft/OctoPi#51]
hi Guy,

Is it an option to add wiring pi to the image...?! [http://wiringpi.com/]
Really nice library to access the gpio pins om the raspberry pi, i already did some test with this and the octoprint API.

cheers \ joris

**Comment by foosel** [comment]
wiring pi would indeed be a neat addition, I could look into that

**Comment by guysoft** [comment]
Fixed by #142
