### ISSUE TITLE
Plugins not getting tabs- 3B+ on week old daily build

### ISSUE THREAD

**Issue by Heliometrix** [guysoft/OctoPi#510]
Hey, thought I'd put in the bug report because this one is perplexing, using octopi for the first time, running the nightly since the last stable isn't 3B+ compatible. So far I have installed CuraEngine, the Enclosure Plugin, and the Astroprint plugin, and turned them all on in plugin manager, but none of them get their own tabs in the web interface so I can't actually use their functionality. Have tried rebooting, not sure what else to try.

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
