### ISSUE TITLE
Setting up Static Wifi address on Scratch

### ISSUE THREAD

**Issue by conrad9900** [guysoft/OctoPi#511]
Firstly In my network, setting the Pi's address on the router side is not possible.
I had wifi working perfectly on Jesse, set it in fullpageos-wpa-supplicant thanks to Guy with no issues.
After reading several of the posted issues I tried the following.
I set the following in dhcpcd.conf:
iface wlan0 inet static
    wpa-ssid "Wifi_Net"
    wpa-psk "********"
    address   192.168.10.13
    netmask   255.255.255.0
    broadcast 192.168.10.21
I changed nothing in fullpageos-network. The result is no IP address assigned

**Comment by conrad9900** [comment]
Apologies, incorrectly posted in OctoPi, not FullPageOS

**Comment by guysoft** [comment]
Wrong traker
