### ISSUE TITLE
GCode Viewer Inverted to what the printer prints

### ISSUE THREAD

**Issue by TimothyGold** [guysoft/OctoPi#519]
Not a huge issue but just thought I would mention this.  I use a Prusa MK3 and i need to invert control on the y axis.  I think this may be why the GCode Viewer shows an inverted view of the print on the bed to what it is really doing on the printer.

**Comment by John-Mc** [comment]
I get the same thing on my Lulzbot Mini.

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi issue. Please report it to OctoPrint issue tracker.
https://github.com/foosel/OctoPrint/issues/

Also, it might bot be a bug. Your y axis is likely assembled wrong, that would make your printer motor spin move the bed the other way.
