### ISSUE TITLE
Webcam not working with OctoPrinT

### ISSUE THREAD

**Issue by hybridtracer** [guysoft/OctoPi#521]
I have an old Xbox Vision Webcam that is listed in the known working webcams page.

> https://github.com/foosel/OctoPrint/wiki/Webcams-known-to-work

I updated octopi.txt with the listed camera_usb_options after it didn't work out of the box.  This is a fresh image from this morning and updated. Octopi Ver = 0.14.0

> pi@octopi:~/mjpg-streamer $ camera_usb_options="-r VGA -f 10"
pi@octopi:~/mjpg-streamer $ ./mjpg_streamer -i "input_uvc.so $camera_usb_options" -o "output_http.so -w ./www"
MJPG Streamer Version.: 2.0
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: 10
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
Unable to set format: 1196444237 res: 640x480
 Init v4L2 failed !! exit fatal
 i: init_VideoIn failed
pi@octopi:~/mjpg-streamer $

/dev/video0 is there and below is LSUSB Output

> pi@octopi:~/mjpg-streamer $ lsusb
Bus 001 Device 005: ID 0403:6001 Future Technology Devices International, Ltd FT232 USB-Serial (UART) IC
Bus 001 Device 004: ID 045e:0294 Microsoft Corp.
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Anyone have any idea what I can try to get this fixed and working?

**Comment by guysoft** [comment]
This is not a bug, please post in the community forum at http://discourse.octoprint.org/
