### ISSUE TITLE
text in octopi-wpa-supplicant.txt is wrong. wep_key0= <cannot have double quotes>

### ISSUE THREAD

**Issue by tjsoco** [guysoft/OctoPi#528]
I'm using version 1.3.8.

I'm using WEP on my wireless network.
The section in octopi-wpa-supplicant.txt with the error looked like this:
 network={
   ssid="put SSID here"
   key_mgmt=NONE
   wep_key0="put password here"
   wep_tx_keyidx=0
 }
But the wep_key0 is a 26 hexadecimal string.
It doesn't work if it is bracketed by double quotes.
When I put it in double quotes, the WiFi didn't work and I found an error log in the syslog that said the key was too long.
Once I removed the double quotes, WiFi worked fine.

I think the correct octopi-wpa-supplicant.txt line should be changed from:
   wep_key0="put password here"
to:
   wep_key0=26_hexadecimal_character_key_goes_here_without_quotes

Yes, I know I should not be using WEP.
Thanks for Octopi!

#### What did you expect to happen?
I expected wifi to work when I put the encryption key in double quotes.
#### What happened instead?
Wifi didn't work.
#### Did the same happen when running OctoPrint in safe mode?
not applicable
#### Version of OctoPi
1.3.8
#### Printer model & used firmware incl. version
not important
#### Screenshot(s)/video(s) showing the problem:
not needed

**Comment by guysoft** [comment]
Not a bug.
Here is an example from wpa_supplicant source code:
https://github.com/digsrc/wpa_supplicant/blob/master/wpa_supplicant/examples/wep.conf

It depends how you set your WEP key, either as a hex or a string that would be hashed.
