### ISSUE TITLE
Add OctoPi 0.14 to Stable section of Nightly builds page?

### ISSUE THREAD

**Issue by John-Mc** [guysoft/OctoPi#533]
Are you going to add OctoPi 0.14 to "Stable Builds" section of the Nightly builds page? Versions 0.12 and 0.13 are there.

**Comment by guysoft** [comment]
@foosel ?

**Comment by foosel** [comment]
Why are you pinging me, the nightly page is under your control ;)

**Comment by guysoft** [comment]
Fixed
