### ISSUE TITLE
Octopi and 5G

### ISSUE THREAD

**Issue by bill-orange** [guysoft/OctoPi#535]
#### What were you doing? Trying to connect to my 5G network. I can connect but when I edit the config file to include the -5G suffix, no connection.  This is using a B+ PI

1. Using a network that includes a 5G connection and using a PI B+, first connect not using 5G and confirm success.
2. Edit config to the 5G SSID and try to connect
3. Failure!

#### Version of OctoPi Latest RC candidate. 1.3.8/0.150

P.S. I also retested after:

apt-get update
apt-get upgrade
rpi-update

**Comment by guysoft** [comment]
Dod you set your country codr correctly? Other than that I have no way of testing.  I don't have 5G here.

**Comment by Penfold81** [comment]
Do you mean 5G wireless band from your router? I have mine set on 2.4G as it’s all that the pi3 would pick up



Sent from my iPhone

On 25 May 2018, at 06:30, Guy Sheffer <notifications@github.com<mailto:notifications@github.com>> wrote:


Dod you set your country codr correctly? Other than that I have no way of testing. I don't have 5G here.

**Comment by bill-orange** [comment]
Yes, the 5G wireless band from the router. With Raspian, my B+ picks it up just fine. 

Guysoft, I don’t see a country code setting in the supplicant config. DidnInmiss it?

**Comment by guysoft** [comment]
Its at the bottom

**Comment by bill-orange** [comment]
Missed it then. I will set it and report back.

**Comment by bill-orange** [comment]
@guysoft Good catch! It was the country code.  I am in US default was GB.
