### ISSUE TITLE
[Request] NTP Server Option

### ISSUE THREAD

**Issue by nrepian** [guysoft/OctoPi#538]
I've got my OctoPi installation isolated from the internet, as I only require local access (except for updates). Is it possible to add an option to specify an NTP server, so that the system time can be sync'd with a local time server?

**Comment by guysoft** [comment]
Not a bug, please use the community forums at: https://discourse.octoprint.org

http://raspberrypi.stackexchange.com/questions/68811/how-do-i-set-raspbian-to-use-the-primary-time-server-time-nist-gov
