### ISSUE TITLE
How to reset octopi username / password

### ISSUE THREAD

**Issue by Serray** [guysoft/OctoPi#544]
Hey there,

i searched the internet for hours now, only to find entries to octoprint over and over, which is not solving my problem.

I am running octoprint with octopi on my raspberry pi.
I forget my username or password to login onto my raspberry pi.
I still can access octoprint and still have my password and username for it.

I need the username / password for my octopi, to login via SSH.
I tried to login to my raspberry pi locally, but it also asks me for username and password.
Is there any way to reset it or grant me access?

Greetings (couldnt find any other place to ask that)

**Comment by guysoft** [comment]
This is not a bug, please use the OctoPrint community forum at: https://discourse.octoprint.org/
You will need to obtain a root console somehow and run passwd.

**Comment by Serray** [comment]
Yeah, but the problem is, all help you get there is for Octoprint, not octopi.
