### ISSUE TITLE
ssh: connect to host ... port 22: Connection refused

### ISSUE THREAD

**Issue by atar-axis** [guysoft/OctoPi#552]
#### What were you doing?

1. Downloaded latest octopi-image
2. uploaded via `sudo dd bs=512k if=./2018-04-18-octopi-stretch-lite-0.15.1.img  of=/dev/mmcblk1 status=progress && sync`
3. inserted into raspberry pi 3b+ and plugged lan cable in
4. tried to connect via `ssh pi@ip-address-as-shown-on-my-routers-webinterface`

#### What did you expect to happen?

A working connection

#### What happened instead?

`ssh: connect to host ip-address port 22: Connection refused`

#### Version of OctoPi

15.1

Before somebody asks: Yep, the ssh file exists in boot.

**Comment by Penfold81** [comment]
Port 22? Have you tried port 80?

Thanks

Dave


Sent from my iPhone

On 6 Oct 2018, at 23:31, Florian Dollinger <notifications@github.com<mailto:notifications@github.com>> wrote:

What were you doing?

  1.  Downloaded latest octopi-image
  2.  uploaded via sudo dd bs=512k if=./2018-04-18-octopi-stretch-lite-0.15.1.img of=/dev/mmcblk1 status=progress && sync
  3.  inserted into raspberry pi 3b+ and plugged lan cable in
  4.  tried to connect via ssh pi@ip-address-as-shown-on-my-routers-webinterface

What did you expect to happen?

A working connection

What happened instead?

ssh: connect to host ip-address port 22: Connection refused

Version of OctoPi

15.1

**Comment by guysoft** [comment]
Do you get the same issue when you use Raspbian lite?

**Comment by atar-axis** [comment]
You mean a clean raspbian image? 
Unfortunately not, everthing works fine then.

**Comment by guysoft** [comment]
I don't understand? You did try and it work? or you didn't?

At the moment you are saying that something that worked for thousands of people, does not work for you. So I have no way to pinpoint there is an error.

**Comment by atar-axis** [comment]
Sorry, your question was if I get the same error using raspbian lite, and my answer was "unfortunately not", so yes - i tried it (a clean raspbian image) and it worked just as expected.
But the octopi image does unfortunately not.

**Comment by atar-axis** [comment]
I found the problem...
I checked the `md5sum` of the .zip file, and it was correct - but i never checked the md5 of the .img - since it was not published on the website. Unfortunately something went wrong while extracting...

So for everybody else, the `md5sum` is `2f7cd2a9aa46464595c0983fe0563a34` for the `2018-04-18-octopi-stretch-lite-0.15.1.img` file.
