### ISSUE TITLE
Octopi resets on reset

### ISSUE THREAD

**Issue by klexxp** [guysoft/OctoPi#553]
#### What were you doing?

Update octoprint from 1.3.8 to 1.3.9 through Web UI
Uploaded model files to print
Installed plugins

#### What did you expect to happen?
On restart:
Octoprint 1.3.9
Uploaded files sill be there
Plugins still installed.

#### What happened instead?

On restart everything is reset back to when I first installed OctoPi. 
Still on Octoprint Version 1.3.8, 
No Uploaded files
No plugins installed.

#### Did the same happen when running OctoPrint in safe mode?

yes

#### Version of OctoPi

0.15.1

#### Printer model & used firmware incl. version

Anet A6
Marlin 1,1,9
Rpi 3B+

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by guysoft** [comment]
Can you please test if your SD card is able to write files? When an SD card dies it will not write new files.
Also, posting ``octoprint.log`` since this is an OctPrint issue.

**Comment by klexxp** [comment]
Okay, Good to know. I'l test that and report back. Thx

**Comment by klexxp** [comment]
It was the SD Card. Now I couldn't write to it anymore. Guess it died a slow death. Thanks
