### ISSUE TITLE
The "pi" user does not exist on armbian by default.

### ISSUE THREAD

**Issue by mr-miky** [guysoft/OctoPi#555]
In raspbian the image of the uSD already contains the default  user **pi** with **raspberry** password and is among the suders.

On armbian the image of the uSD does not have users except root and at the first login it allows to create the "normal" user. After connecting as root in ssh,  you can create the user **pi** with the **raspberry** password and insert it into the sudoers.

The problem is that the build_dist script starts from the assumption that **pi** exists and changes the group membership, the mode of operation of the sudo etc causing the failure of the script since it does not find **pi** among the sudoers ... .

In practice you need to write armbian for OrangePiZero on a uSD, start OrangePiZero, create the user pi, get the image from the uSD and pass it to build_dist as an image of the variant.

**Comment by guysoft** [comment]
What are you trying to do?
Are you building or using an existing build?
Of building,  please attach ```build.log``

**Comment by guysoft** [comment]
Closing due to no response
