### ISSUE TITLE
RaspberryPi 3B+ w/2.1 Camera Not working

### ISSUE THREAD

**Issue by jhihn** [guysoft/OctoPi#559]
I downloaded the latest release of octopi (my first OctoPi experience), installed it on a Raspber Pi 3b+ (brand new) with a 2.1 camera module.

The camera was detected but would not work:

    pi@octopi:~ $ vcgencmd get_camera
    supported=1 detected=1
    pi@octopi:~ $ raspistill -o /tmp/foo.img
    mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
    mmal: camera component couldn't be enabled
    mmal: main: Failed to create camera component
    mmal: Failed to run camera app. Please check for firmware updates

I fixed it with:

    pi@octopi:~ $ sudo rpi-update
    pi@octopi:~ $ sudo reboot

**Comment by guysoft** [comment]
You didn't provide the version of OctoPi. Have you tried the nightly?
I have no 2.1 camera module to test against.

**Comment by guysoft** [comment]
The release announcement of the camera is after OctoPi 0.15.1 is released, although there are no release notes saying anything about the camera. I suggest you try the nightly and report. That should work. And we could add it to our release notes.

**Comment by guysoft** [comment]
Closing if no reply

**Comment by jhihn** [comment]
Worked eventually.
