### ISSUE TITLE
Cron not working

### ISSUE THREAD

**Issue by ToXIc-Dev** [guysoft/OctoPi#562]
#### What were you doing?

Trying to run a cron job

#### What did you expect to happen?
The job to run

#### What happened instead?
Nothing

#### Version of OctoPi
OctoPi 0.15.1

**Comment by guysoft** [comment]
Does it work for you on raspbian lite?

**Comment by ToXIc-Dev** [comment]
I haven't tried, ill have to flash it and see what happens.

**Comment by guysoft** [comment]
Its highly likely that you are just using cron the wrong way, or its not
installed.

**Comment by ToXIc-Dev** [comment]
It turned out to be an issue with my script running in cron, my bad.
