### ISSUE TITLE
Upgrade use ssh from 1.3.9 to 1.3.10

### ISSUE THREAD

**Issue by userosos** [guysoft/OctoPi#563]
Hello! Everyone! I can not upgrade my octoprint from 1.3.9 to 1.3.10 from web. How can i get 1.3.10 use ssh? Sorry for noobs question.

**Comment by guysoft** [comment]
1.3.10 is not released yet. For information on how to upgrade to RC see https://discourse.octoprint.org/t/how-can-i-switch-the-branch-of-the-octoprint-installation-on-my-octopi-image/206

**Comment by John-Mc** [comment]
1.3.10 was released on December 10.
[](https://octoprint.org/blog/2018/12/10/new-release-1.3.10/)

**Comment by guysoft** [comment]
Spoke to @foosel two days ago and she said "release today" and missed that.
Reguardless, this is an OctoPrint issue, not an OctoPi issue, so you should report it to https://github.com/foosel/OctoPrint/issues/

**Comment by foosel** [comment]
[How to update manually via SSH is explained in the FAQ](https://discourse.octoprint.org/t/how-can-i-update-the-octoprint-installation-on-my-octopi-image/207).
