### ISSUE TITLE
It's not possible to click "Proceed" in the update dialog when multiple notifications are displayed

### ISSUE THREAD

**Issue by DominikPalo** [guysoft/OctoPi#565]
#### What were you doing?
I'm trying to update OctoPi.

#### What did you expect to happen?
To be able to click the "Proceed" button also when multiple notifications are displayed.

#### What happened instead?
The "Proceed" button is overlapped with a notification box.

#### Version of OctoPi
1.3.10rc3

#### Suggestion
Consider using the highest z-index for modal windows/dialogs.

#### Screenshot(s)/video(s) showing the problem:
![image](https://user-images.githubusercontent.com/1623257/50730381-64edbf00-114c-11e9-8dfd-84f08068938c.png)

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi issue. Please post it to the OctoPrint issue tracker at: https://github.com/foosel/OctoPrint/issues/

I can already tell you this is not a bug, you are just not marking news message as read and they are blocking your screen
