### ISSUE TITLE
octoprint does not connect automatilc on boot

### ISSUE THREAD

**Issue by sbias** [guysoft/OctoPi#570]
Hi,
(i hope this is not a dup, couldn't find this problem here)
while booting OctoPi, octoprint starts up. I set up automatic connect to the printer. But is most cases it does not work and i have to connect manual - which works fine.
After some debugging i found out, the process ModemManager is blocking the device while octoprint starts up. removing that package ( apt remove modemmanager ) solved it.
My recommendation: remove it by default. I think its not needed in octopi :)

**Comment by sbias** [comment]
Hmm, just installed a new image of octopi, seems modemmanager has been removed already? can somebody confirm this? If correct, this issue can be closed.

**Comment by guysoft** [comment]
modemmanager is not shipped with OctoPi, this issue can be closed.
![Screenshot_20190506_142811](https://user-images.githubusercontent.com/325670/57222432-35bc6100-700b-11e9-9a3a-cf2fcc64c1bf.png)
