### ISSUE TITLE
Deleted file - Print stopped (prusa mk3s) mid print 

### ISSUE THREAD

**Issue by davzarek** [guysoft/OctoPi#586]
1. Deleted a print file - not the current one printing
2. Print stopped mid in print

#### What did you expect to happen?
-not stop the print

#### What happened instead?
-print stopped

#### Did the same happen when running OctoPrint in safe mode?
NA

#### Version of OctoPi
-latest stable image 1.3.10

#### Printer model & used firmware incl. version
prusa mk3s

FAQ.
y

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/
