### ISSUE TITLE
RaspiCam is not operating

### ISSUE THREAD

**Issue by thomasdr1** [guysoft/OctoPi#59]
RaspiCam is not operating with octopi.
"raspistill Camera App v1.3.8

Width 2592, Height 1944, quality 85, filename test.jpg
Time delay 5000, Raw no
Thumbnail enabled Yes, width 64, height 48, quality 35
Link to latest frame enabled  no
Full resolution preview No
Capture method : Single capture

Preview Yes, Full screen Yes
Preview window 0,0,1024,768
Opacity 255
Sharpness 0, Contrast 0, Brightness 50
Saturation 0, ISO 0, Video Stabilisation No, Exposure compensation 0
Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
Rotation 0, hflip No, vflip No
ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates"

All Raspbian updates and firmware are up to date.
The camera runs on standard Raspbian.

**Comment by guysoft** [comment]
@foosel Did you see this before on your camera?
I have no hardware to test it on.

**Comment by guysoft** [comment]
Related #31

**Comment by guysoft** [comment]
Duplicate
