### ISSUE TITLE
Microsoft VX-7000 webcam: additional_brokenfps_usb_devices

### ISSUE THREAD

**Issue by numanair** [guysoft/OctoPi#598]
#### What were you doing?

Using a Microsoft VX-7000 webcam, removing the -f parameter was required to get an image.

lsusb reports the ID: 045e:0723

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by guysoft** [comment]
Can you please provide more details? You left all the rest and have no clue what went wrong, what version are you using and so on.

**Comment by numanair** [comment]
My apologies, I assumed the other sections were not needed in this case.
I have tested against Octopi 0.14 through 0.16.
The webcam works fine, it seems it just needs to be added to additional_brokenfps_usb_devices or have the -f parameter removed.

**Comment by guysoft** [comment]
There is a page documenting that you can update here:
https://github.com/foosel/OctoPrint/wiki/Webcams-known-to-work

**Comment by guysoft** [comment]
@foosel Is the the place to update? Right?
https://github.com/foosel/OctoPrint/wiki/Webcams-known-to-work

**Comment by foosel** [comment]
Currently yes.

**Comment by guysoft** [comment]
Ok, closing this @numanair upldate it in the wiki page
