### ISSUE TITLE
RPi 2 support

### ISSUE THREAD

**Issue by MoonshineSG** [guysoft/OctoPi#60]
will there be a build for the new RPi 2 ?

**Comment by guysoft** [comment]
Hey,
There are nightly builds available at http://docstech.net/OctoPiMirror/nightly/
They should work with RPi 2. I do't have one to test, and it would be great if someone will confirm he it works, and which nightly build

**Comment by emericklaw** [comment]
I have used the 06-02 nightly on a new RPi 2 but get 405: Method Not Allowed when requesting the main page. I tried to access other resources like images and style sheets and all I tried failed.

Networking and SSH have worked fine, yet to test the webcam.

**Comment by guysoft** [comment]
@foosel it might be the HAProxy rules that were changed?

**Comment by guysoft** [comment]
I think #50 caused a regression. Not sure how to fix it :-/

**Comment by guysoft** [comment]
@emericklaw Ok merged a fix from @foosel . It should build in this nightly, and you can test it out. Or just apply it yourself and test.

**Comment by emericklaw** [comment]
I updated the haproxy.cfg and after a reboot all appears to be fine, I have not been able to test connecting to a printer yet.

**Comment by guysoft** [comment]
2015-01-31-octopi-0.11.0-2015-02-07.zip build should have the fix
