### ISSUE TITLE
Raspberry don't start anymore

### ISSUE THREAD

**Issue by Grazulex** [guysoft/OctoPi#605]
<Hello,

I have install octopi on a Raspberry 3 B+ with a mSATA SSD 120gb.
I have use this installation without issues 2-3 days but one days, the Raspberry won't start anymore...I have the red power led and the blue led of the SSD but nothing happend.

I have order a new Raspberry and have install again octopi on the SSD. +/- 10 secs I have see the led blink and I was sure that everything was OK but when I have connect the USB cable to my Ender 3 pro printer...I had the same issue and I can't not anymore the system on the Raspberry.

I have try to connect the system to a HDMI screen to try to see something but I see nothing...system don't start anymore.

It's my second rasbperry in 2 days :frowning:

Can somebody explain me what's the issue ? what's wrong?
Thanks

JMS

**Comment by guysoft** [comment]
Sounds either like an SD card corruption issue or a power issue as my first bet.
This isn't really a bug so please post it to the OctoPrint community forum:
https://discourse.octoprint.org/
