### ISSUE TITLE
RPI 4 - Pull Up Resistor

### ISSUE THREAD

**Issue by ETE-Design** [guysoft/OctoPi#617]
Seems like it is not possible to set the Pull Up on the GPIO

root@octopi:/home/pi# gpio -g mode 14 up
root@octopi:/home/pi# gpio -g read 14 
0 
root@octopi:/home/pi#
There's nothing connected to BCM Pin 14, so the result should be 1

**Comment by guysoft** [comment]
I am not sure this is a bug, its not something we modify.
Please first ask in the OctoPrint community forum
 https://community.octoprint.org/

**Comment by jonasbits** [comment]
check out libgpiod https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/tree/README

**Comment by guysoft** [comment]
Closing if no reply

**Comment by guysoft** [comment]
@ETE-Design Did you solve your issue? Please share if you did.

**Comment by ETE-Design** [comment]
Sorry No, haven't had time to look at it :-(
