### ISSUE TITLE
Switch to xz for compression instead of zip.

### ISSUE THREAD

**Issue by CRCinAU** [guysoft/OctoPi#628]
So i understand that the compression to zip file is there to make things easier for folks, but there's a LOT of extra bytes floating around that don't need to be.

eg:
octopi-buster-lite-0.17.0.zip -> 720,197,234
2019-09-26-octopi-buster-lite-0.17.0.img -> 2,879,389,696

Compressing with xz:
2019-09-26-octopi-buster-lite-0.17.0.img.xz -> 462,746,292

That's a saving of 257,450,942 bytes per image!

On a linux system, writing the image is just as easy - and you don't even have to unzip it first:

`xz -dc 2019-09-26-octopi-buster-lite-0.17.0.img.xz | sudo dd of=/dev/sdb status=progress oflag=direct`

The above is multi-threaded, so you get maximum performance, and doesn't use the disk cache - so when the write is finished, so is your image.

If you want to add more options to get more speed, you can use:
`xz -T0 -dc 2019-09-26-octopi-buster-lite-0.17.0.img.xz | sudo dd of=/dev/sdb status=progress oflag=direct bs=1M iflag=fullblock`

**Comment by guysoft** [comment]
At the moment I am mimicing raspbian who publish as ``.zip``. I rather be available rather than light. Rather sacrifice the ~250MB for that. If you are willing to host a mirror you are welcome. Closing for now.
