### ISSUE TITLE
CAM LOG Missing

### ISSUE THREAD

**Issue by rgrugan** [guysoft/OctoPi#629]
#### What were you doing?

1. Trying to review cam log to identify why cam stops working

#### What did you expect to happen?

log would be in the documented location: /var/log/webcam.log

#### What happened instead?

No log can be found

#### Version of OctoPi

0.17.0

**Comment by guysoft** [comment]
What is the output of:
```
systemctl status webcamd
```
?

**Comment by guysoft** [comment]
Closing if no reply

**Comment by guysoft** [comment]
What is the output of:
```
systemctl status webcamd
```
?
