### ISSUE TITLE
[ENHANCEMENT] Fedora uses the p7zip package (not p7zip-full)

### ISSUE THREAD

**Issue by amrsoll** [guysoft/OctoPi#631]
#### What were you doing?

I was trying to create an image of OctoPi following the README

#### What did you expect to happen?

To install all the requirements as given for apt-get

#### What happened instead?

The dnf package manager uses `p7zip` instead of `p7zip-full`

Just a heads' up if you intend to add it to the README.

Everything else seems to work flawlessly so far :+1: 

I have read the FAQ.

**Comment by guysoft** [comment]
This is why you should use the Docker or Vagrant build method. I can't
support multiple Linux distribution builds.

**Comment by amrsoll** [comment]
Sounds good, I'm trying out Vagrant :smile:
