### ISSUE TITLE
Octopi shutdown without warning 

### ISSUE THREAD

**Issue by Rivenin** [guysoft/OctoPi#632]
I have octopi setup and has been working flawlessly, i have an external touchscreen hooked up next to it and was cleaning my office when i heard it pause. i looked over and the raspberry pi had shut itself off

i pulled the logs after turning it back on and i'm not noticing anything except for "shutting down, processing shyutdown event, this will be our last event
event loop shut down
goodbye! 

(uploaded logs) 

i do have a power button setup to turn the pi on and off via a script, but might be disabling that if you think that is causing it? 
i did just run through a few hour print last night without any issue, so it just seems a bit odd that it would stop this morning. 

[octoprint.log](https://github.com/guysoft/OctoPi/files/4200009/octoprint.log)

**Comment by guysoft** [comment]
Hey, this is an OctoPrint issue, not an OctoPi issue. Moreover if this is a vanilla install its unlikely a bug, please post to the OctoPrint community to sovle your issue: https://community.octoprint.org/
