### ISSUE TITLE
Logitech, Inc. Webcam C250 not working out of the box

### ISSUE THREAD

**Issue by ValerchikV** [guysoft/OctoPi#638]
After i added 
additional_brokenfps_usb_devices=("046d:0804") 
to octopi.txt it started working.
So please update coresponding files.

**Comment by guysoft** [comment]
@ValerchikV Woud appriciate if you send a Pull request with the fix.
The file to update is: https://github.com/guysoft/OctoPi/blob/devel/src/modules/octopi/filesystem/home/root/bin/webcamd#L18
