### ISSUE TITLE
additional_brokenfps_usbdevices=(046d:0825)

### ISSUE THREAD

**Issue by midow** [guysoft/OctoPi#657]
#### What were you doing?

Logitech C270 USB camera would not work, fixed by activating the broken devices line.

1. ...
2. ...
3. ...

#### Version of OctoPi

0.17.0

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by guysoft** [comment]
Can you provide what you have added in the line for the camera to work?
Or even better - send a PR to the file: https://github.com/guysoft/OctoPi/blob/devel/src/modules/octopi/filesystem/home/root/bin/webcamd#L18

**Comment by midow** [comment]
I added the line shown in the subject. The Logitech C270 is 046d:0825

via phone

**Comment by cxcorpx** [comment]
hi, i'm new in octoprint, i have 2 camera and both run slow fps, maybe u can help me to fix this i have the c920 and c930e i have 10 days reading post and nothing that can help me to fix this, if u can help i will be really happy i don't want to sell my cameras.

**Comment by guysoft** [comment]
@cxcorpx I warmly suggest you ask in the OctoPrint community forum at: https://community.octoprint.org/
