### ISSUE TITLE
Free/Used Space is Blank on rc3. and Unable to successfully upload gcode.

### ISSUE THREAD

**Issue by dcodom** [guysoft/OctoPi#667]
#### What were you doing?

I am using OctoPrint rc3. I have ran into two issues....
I just upgraded from the latest stable release.

Since upgrading I no longer see what the drive space used or available is.
and
I just tried the drag and drop method along with the manual upload. And the screen never says that it is finished saving. If I refresh the browser, it shows the file in the list, but I am not sure it is all there.

#### Version of OctoPi
1.4.1rc3

#### Printer model & used firmware incl. version
Ender3 Pro 
RaspPi Version 3b+

#### Screenshot(s)/video(s) showing the problem:

![image](https://user-images.githubusercontent.com/8545875/88049995-acb01d80-cb1b-11ea-8256-e132168f46c0.png)

I have read the FAQ.

**Comment by dcodom** [comment]
Also when I hit the trashcan to delete the file I tried to upload, the trashcan just spins and spins.

**Comment by dcodom** [comment]
fyi.... I just rolled it all back to 1.4.0 and it is all working as it should. I can go back to rc3 when/if this can be resolved.

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi issue. Please report it to OctoPrint issue tracker.
https://github.com/foosel/OctoPrint/issues/
