### ISSUE TITLE
Unable to use web GUI

### ISSUE THREAD

**Issue by kpayney1** [guysoft/OctoPi#675]
What were you doing?

Starting a print. Web UI dropped out and have since been unable to use it.

What did you expect to happen?

A Print

What happened instead?

Printer started to heat up then paused and have been unable to load octopi since. 

Did the same happen when running OctoPrint in safe mode?
Unable to set safe mode

Version of OctoPi
0.17.0

Printer model & used firmware incl. version

CR10-S running klipper

Methods completed so far to try and fix:
Replaced Raspberry Pi 3+ with new item,
Replaced power supply,
Replaced memory card,
Fresh install of old and new memory cards,
Changed power cables,
Changed IP address on modem,
Ran raspberry without connecting to printer. 
Trying to get the logs results in this

-bash: /home/pi/.octoprint/logs/octoprint.log: Permission denied

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi issue, please post it to the OctoPrint community at: https://discourse.octoprint.org/
