### ISSUE TITLE
Request - Unknown IP Addresses

### ISSUE THREAD

**Issue by Doubledeucedavis** [guysoft/OctoPi#682]
My wifi automatically shut down my RaspberryPi because it was detecting unknown IP addresses. Anywhere from Russia to Poland to Canada. I reset my Pi and I do not want to reinstall Octoprint because of the threats my Wifi blocked. It may have been a plugin but I do not have a list of the plugins I had.

**Comment by Doubledeucedavis** [comment]
Any help is greatly appreciated. I love using it and it streamlines everything.

**Comment by guysoft** [comment]
I am not sure how OctoPi could be related to this.
You could install a firewall on the RaspberryPi and configure it to receice only local network traffic:
Also, you might have a plugin that is making remote requests.
https://www.raspberrypi.org/documentation/configuration/security.md

@foosel saw anything like that?

**Comment by foosel** [comment]
> @foosel saw anything like that?

Nope. Sounds unrelated

**Comment by Doubledeucedavis** [comment]
Sorry for taking away from your time. I decided to re install octopi and not install many plugins.
