### ISSUE TITLE
Default tmpfs size does not allow updates

### ISSUE THREAD

**Issue by Salamandar** [guysoft/OctoPi#686]
Recent Octoprint requires 150MB of available space in /tmp, but /etc/fstab says size=64M of tmpfs.
Could it be changed to a more sane value ? ;)

Thanks !

**Comment by guysoft** [comment]
1. What version of OctoPi?
2. Can you please share your ``/etc/fstab``? I don't see that in mine.

**Comment by Salamandar** [comment]
Hi, i was on 0.16.0. Just upgraded to 0.17.0 and it seems that's not the case anymore... Sorry!Closing.
