### ISSUE TITLE
[Request] Remove dead download links from the releases

### ISSUE THREAD

**Issue by crazyimp** [guysoft/OctoPi#691]
The "Download it at: https://storage.googleapis.com/octoprint/stable/octopi-buster-lite-0.17.0.zip" links on https://github.com/guysoft/OctoPi/releases are dead and can be removed / replace with a hint for the attached assets of the release.

I have read the FAQ.

**Comment by guysoft** [comment]
Thanks for noting. We should re-route them to new urls.

**Comment by foosel** [comment]
I've taken the liberty to fix the links on the releases page to point at the assets attached to the release. This can imo be closed now.
