### ISSUE TITLE
Egalax touchscreen support

### ISSUE THREAD

**Issue by tiagojanz** [guysoft/OctoPi#70]
# I usually do this part by ssh

sudo apt-get update
sudo apt-get upgrade
wget https://github.com/raspberrypi/linux/archive/rpi-3.6.y.tar.gz
tar -zxvf rpi-3.6.y.tar.gz
 sudo apt-get install git libncurses5 libncurses5-dev qt4-dev-tools build-essential
cd linux-rpi-3.6.y/
make mrproper
cp arch/arm/configs/bcmrpi_defconfig .config
# this part need a  x session, so login and startx  than  open terminal   and type

cd linux-rpi-3.6.y/
make xconfig
# look for input devices then select egalax touch   AND touchscreen usb
# click in the floppy icon to save and close the application

make

sudo make modules_install
sudo cp arch/arm/boot/Image /boot/new_kernel.img

sudo nano /boot/config.txt
###### ## INSERT

kernel=new_kernel.img
###### 
###### ## UNCOMENT
# disable_overscan=1
###### 
###### ################ CALIBRATE TOUCHSCREEN

sudo apt-get install libx11-dev libxext-dev libxi-dev x11proto-input-dev

 wget http://github.com/downloads/tias/xinput_calibrator/xinput_calibrator-0.7.5.tar.gz

tar -zxvf xinput_calibrator-0.7.5.tar.gz

cd xinput_calibrator-0.7.5

./configure

 make

sudo make install
# then run the application and open the calibration utility in preferences menu (I know you can't test it, but for the sake of completeness)
# after the calibration finishes it will open a terminal window with the following information

Section "InputClass"
    Identifier    "calibration"
    MatchProduct    "eGalax Inc. USB TouchController"
    Option    "Calibration"    "42 1959 1837 115"
EndSection
# copy it into 99-calibration.conf

sudo mkdir /etc/X11/xorg.conf.d
sudo nano /etc/X11/xorg.conf.d/99-calibration.conf
# that's it .... reboot  and go
###### 

 update  forgot to add make after xconfig

**Comment by seefood** [comment]
no need for make xconfig, there was menuconfig last time I checked :)

**Comment by tiagojanz** [comment]
didn't know that!!! it could saved me some time.

**Comment by seefood** [comment]
Well, when you compile Linux kernel for 21 years, you learn a trick or two :-)
(I actually only ever used make xconfig once and hated it)

**Comment by seefood** [comment]
Oh wow... it even has a Wikipedia entry...
https://en.wikipedia.org/wiki/Menuconfig

**Comment by tiagojanz** [comment]
hehe did that too ;)

On Thu, Feb 12, 2015 at 11:33 AM, Ira <notifications@github.com> wrote:

> Oh wow... it even has a Wikipedia entry...
> https://en.wikipedia.org/wiki/Menuconfig
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guysoft/OctoPi/issues/70#issuecomment-74056907>.
>



-- 

*Tiago Torre do Vale*
*Investigação e Desenvolvimento*


RESOPRE, S.A
Tel.: (+351).218.310.630 | Fax: (+351).218.310.639 <br>
Telem.: (+351).919.271.569
 E-mail:tiago.vale@resopark.com | URL: www.resopark.com

**Comment by guysoft** [comment]
Legacy hardware, closing.
