### ISSUE TITLE
0.17.0 on pi 4B - bootloader compatibility

### ISSUE THREAD

**Issue by telephasicworkshop** [guysoft/OctoPi#714]
I will try 0.18.0 RC2 next, but for what it's worth, I just noticed that 0.17.0 compatibility on pi 4B seems down to bootloader version:
DOES BOOT on pi 4B with bootloader Sep 3 2020
DOES NOT BOOT with bootloader Mar 19 2020
For info.

**Comment by guysoft** [comment]
Ok, TBH I can't really do anything about it. We got only a handful of problems on a 4B on 0.17.0. 0.18.0 RC2 is indeed your next stop

**Comment by telephasicworkshop** [comment]
Yeah no problem.
Indeed, whatever it was, it is solved in 0.18.0 RC2 (both bootloaders working).
As I said, just for info. Fine to close it. Thanks for getting back though.
