### ISSUE TITLE
[Request] Disable wifi sleep

### ISSUE THREAD

**Issue by hawkeyexp** [guysoft/OctoPi#721]
During using octoscreen i noticed sometimes reconnects by octoscreen which was caused by wifi sleep policy.

I disabled it with "iw dev wlan0 set power_save off" inside /etc/rc.local and the disconnects was gone.
I recommend disabling wifi sleep in sdcard image possible as ifup script etc :-)

**Comment by guysoft** [comment]
That's really cool. I am trying to figure out where is the best place t place this.
[Here](https://forum.clockworkpi.com/t/how-to-disable-wifi-power-save-to-prevent-disconnects/933) its suggested at ``/etc/network/if-up.d/powesave_off`` before the ``exit 0`` line.

**Comment by guysoft** [comment]
After trying to get it to work with ``/etc/network/if-up.d/powesave_off`` it seems that method just doesn't work anymore. So using rc.local. Hope some brave contributor comes along and figures out how to do this nicer, possibly taking other interface names in to account.

**Comment by guysoft** [comment]
Fixed, needs to be tested
