### ISSUE TITLE
[Request] Add image to Raspberry Pi Imager

### ISSUE THREAD

**Issue by janis-ax** [guysoft/OctoPi#726]
In Raspberry Pi Imager is a section named "Other specific purpose OS" maybe there is a option to add OcotPi as an image.

**Comment by guysoft** [comment]
I think it requires opening an issue here and writing a json. Will look in to it
https://github.com/raspberrypi/rpi-imager/issues

**Comment by guysoft** [comment]
Requested: https://github.com/raspberrypi/rpi-imager/issues/162

**Comment by guysoft** [comment]
![Screenshot_20210311_173308](https://user-images.githubusercontent.com/325670/110812032-ef338f80-828f-11eb-95e5-44a7b0035d46.png)
Its now part of rpi-imager, closing.
