### ISSUE TITLE
[Request] support Raspbian Desktop.

### ISSUE THREAD

**Issue by spacecabbie** [guysoft/OctoPi#735]
Any change for Raspbian Desktop support ?
The Pi is to limited the more you do with it (like klipper) 

Raspbian desktop with for example (https://learn.pi-supply.com/make/getting-started-with-the-rtk-gpio-board/)
Can be a good alternative.

**Comment by guysoft** [comment]
There is a script to install raspsbian desktop on OctoPi.

[/home/pi/scripts/install-desktop](https://github.com/guysoft/OctoPi/blob/devel/src/modules/octopi/filesystem/home/pi/scripts/install-desktop)

**Comment by guysoft** [comment]
Closing no reply

**Comment by spacecabbie** [comment]
Oww sorry din't see your reply before but its not the same I am talking about: Raspberry Pi OS:
https://www.raspberrypi.org/software/operating-systems/

**Comment by guysoft** [comment]
OctoPi is already built on top of RaspberryPi OS using CustomPiOS. I has a script that lets you install the full desktop of RPiOS of you need it. And its not shipped by default because it would bloat the image by a few GB and would slow performance.

So I am not sure what exactly you are asking for apart from that.

**Comment by spacecabbie** [comment]
Yes but I do not mean the default raspberrypi Os but the one for desktop "Raspberry Pi Desktop" mean to be installed on x86 architecture.

**Comment by Willmac16** [comment]
Octoprint will run on pretty much anything. You just need to do a manual install [click here and scroll down to installing manually](https://octoprint.org/download). The gpio isn't used by octoprint core; however, many plugins are written with the target user-base of raspberry pi users, so you may need to find ways to get specific plugins to work with that external gpio usb device that you linked.

**Comment by spacecabbie** [comment]
From the run around I am getting I take it means no it will not be supported just say that then.
