### ISSUE TITLE
Nightly builds do not seem to have working MJPEG for the raspicam module 

### ISSUE THREAD

**Issue by jwcrawley** [guysoft/OctoPi#765]
Greetings, 

I just tried using the NIGHTLY http://unofficialpi.org/Distros/OctoPi/nightly/2022-02-08_2022-01-28-octopi-bullseye-armhf-lite-1.0.0.zip 

And in the /home/pi/mjpg-steamer seems to not be the raspicam branch. The relevant libraries that allow the rpicam to work aren't there.

Search across the system using "sudo find / | grep input_raspicam.so" provides no valid results.

(I also downloaded the current stable install and the relevant library **was** present.)

**Comment by guysoft** [comment]
Hey, just tested 1.0.0 RC1 and it seems to work now both rpi cam and usb cams, both 32bit and 64bit
