### ISSUE TITLE
Octoprint on TrueNas Jail

### ISSUE THREAD

**Issue by riccardokhm** [guysoft/OctoPi#775]
Hi Everyone,
I successfully installed Octoprint on a TrueNas jail as explained in https://community.octoprint.org/t/setting-up-octoprint-on-freenas-11-3-server-inside-iocage-jails/7440/28, updating pyhton and all the other packages. The question is now how to configure the webcam usage? I am not able to find the octopi.txt file, at least in the same location as in Ubuntu. Does mjpg come already installed with Octoprint? Has anyone tried this solution? The FreeBSD versione is 12.3.
Thanks in advance,

**Comment by guysoft** [comment]
Octopi.txt is part of OctoPi, not OctoPrint.
This is the issue tracker of OctoPi, not OctoPrint. From what I understand you didn't install OctoPi.
