### ISSUE TITLE
[doc][enhancement]: Default settings on raspi zero 2 W don't work with serial connection to Prusa MK3

### ISSUE THREAD

**Issue by pfiaux** [guysoft/OctoPi#779]
#### What were you doing?

Setting up a new Raspberry Pi Zero 2 W with a Prusa printer (fresh install)

1. Flash OctoPi on to SD card for a Raspberry Pi Zero 2 W (with wifi config)
2. Connect Raspbery Pi Zero 2 W via the GPIO serial connection to prusa MK3

#### What did you expect to happen?

On OctoPrint connecting via the auto settings didn't work

#### What happened instead?

Only `AUTO` was listed and connection kept failing.

Steps that solved the issue:
- Under Settings > Serial Connection I had to add `/dev/ttyAMA*` to the additional ports (already present on the pi when connected via ssh)
- added `dtoverlay=disable-bt` on new line at end of `/boot/config.txt`
- removed `console=serial0,115200` from `/boot/cmdline.txt`
- run `sudo systemctl disable hciuart.servic`
- run `sudo systemctl disable bluetooth.service`
- run `sudo reboot`

Then I was able to connect without issues. **For me the problem is solved**, I'm reporting it as it could help other or either improve documentation or setup scripts. Feel free to close the issue if this isn't the correct place to report it :)

The steps after the first were documented here:
https://help.prusa3d.com/en/article/octoprint-configuration-and-install_2182#configure-rpi-zero-w-gpio

I was wondering however if it would be possible to include these settings while flashing the card or in the base image?

Some might be specific to the pi zero 2 so it might not be possible to have a generic solution so maybe documenting them helps, not sure if octopi or octoprint is the right place (I searched there first and then eventually found the correct page on prusa).

#### Did the same happen when running OctoPrint in safe mode?

n/a

#### Version of OctoPi

`OctoPrint 1.7.3 Python 3.7.3 OctoPi 0.18.0`
#### Printer model & used firmware incl. version

`Prusa MK3s 3.10.1-4697`

#### Screenshot(s)/video(s) showing the problem:

n/a

I have read the FAQ.

**Comment by guysoft** [comment]
I cant maintain the instructions for pursa. If they want they can create a custom image using CuatoPizer and we can host it on [pi-imager](https://github.com/guysoft/pi-imager/releases).
