### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by Budman1758** [guysoft/OctoPi#786]
I noticed a curious thing printing a rather large gcode file.  See the attached screenshot.  The progress indicator and the file printed/filesize numbers don't match up very well.  The file being printed is just under 130 Megs and the file size shown in the print time area is only 101.0 meg. See also the printed percentage is 103 percent.

The print itself is doing fine. Is there a file size limit on those particular indicators?  Let me know what other info is needed. (If any)  

![image](https://user-images.githubusercontent.com/6570134/178839181-052f8252-de5e-406f-a209-c7e25ce827e7.png)

OctoPrint 1.8.1 Python 3.7.3 OctoPi 0.18.0
Raspberry Pi 4 2 GIG RAM

**Comment by chudsaviet** [comment]
Its a bug fort OctoPrint, not OctoPi.
Please report at https://community.octoprint.org/ .

**Comment by guysoft** [comment]
As mentioned above by @chudsaviet . This is an OctoPrint related issue
