### ISSUE TITLE
[Request] Cookie-less sign in

### ISSUE THREAD

**Issue by D3MZ** [guysoft/OctoPi#794]
Once the user signs in, they get redirected to their portal that works for that session ([see this](https://www.loginradius.com/blog/engineering/cookie-based-vs-cookieless-authentication/) and [JWT](https://jwt.io)) 

Cookies are problematic for a variety of reasons, and [the internet is moving away from this authentication](https://www.cookiebot.com/en/google-third-party-cookies/). 
I personally try and browse with cookies blocked, but it breaks services like this unfortunately which means I have to re-enable cookies across the entire browser to work with Octopi.

**Comment by guysoft** [comment]
Its a bug of OctoPrint, not OctoPi.
Please report at https://community.octoprint.org/ or https://github.com/OctoPrint/OctoPrint/issues
