### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Firedogs2x** [guysoft/OctoPi#803]
I downloaded version "octopi-0.18.0-1.8.6-20221018093204" and used Pi Imager 1.7.3 to create a new SD card.
I setup all of my information using the advanced setup.
I have logged in using SSH, got VNC to work.
Now I typed in my IP address and get the login website page.
I type in my username and password I then get the error that either my username or password is wrong.
I have even tried to use the default username and password, but I get the error message.
How do I fix this?

Thank you for your help.

**Comment by guysoft** [comment]
You are asked in the wizard to create a username and password - there is no default login on the web page.

Also you might have set a different ssh user and password on rpi imager.

I don't think this is an issue with the image and you should ask about this at: https://community.octoprint.org/
