### ISSUE TITLE
enabling autostart of OctoPiPanel

### ISSUE THREAD

**Issue by korneelb** [guysoft/OctoPi#81]
Hi;

once i now enable the touchscreen, i have to manually go in and select the octopipanel script at every reboot. can you change the script so it adds itself to the autostart scripts once selected? or perhaps something like
"./scriptname -autostart $true" and ",.scriptname -autostart $false" to enable and disable...

**Comment by jonaslorander** [comment]
https://github.com/jonaslorander/OctoPiPanel#automatic-start-up

**Comment by korneelb** [comment]
I understand but does this work on OctoPiPanel as well?

**Comment by korneelb** [comment]
i mean OctoPi.. since things sometimes work different in this..

**Comment by nophead** [comment]
Yes it worked for me.

**Comment by korneelb** [comment]
so i did exactly that. but does not start automatically. any way to verify what is happening? running the script manually works.

**Comment by guysoft** [comment]
@jonaslorander We should really link that in the OctoPi readme page.
Can anyone who is not me do it?

**Comment by mikestreety** [comment]
I tired the OctoPiPanel auto start and doesn't work for me! Any ideas?

**Comment by guysoft** [comment]
Can you post what you did exacly and what output you got?

**Comment by mikestreety** [comment]
I followed this:

https://github.com/jonaslorander/OctoPiPanel#automatic-start-up

No errors, everything seemed to work fine but doesn't work on boot - the screen just shows the terminal.

**Comment by jchristman75** [comment]
Here is what I did for OctoPi, because the service trick did not work for my PiTFT

sudo crontab -e

Then add the line, at the bottom.
@reboot /home/pi/scripts/OctoPiPanel

Save the file (CTRL-O, Enter, CTRL-X) then reboot to test.

**Comment by guysoft** [comment]
OctoPiPanel is legacy, closing.
