### ISSUE TITLE
Have a big disclaimer - this will wipe your Pi 

### ISSUE THREAD

**Issue by hexitex** [guysoft/OctoPi#816]
#### What were you doing?
looking to install octoprint 

1. ...
2. ...
3. ...

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by cp2004** [comment]
When following the instructions on https://octoprint.org/download, using the RPi imager, I am presented with this:
![image](https://user-images.githubusercontent.com/31997505/230798150-8f176e8e-8349-4d31-be69-39187316320e.png)

**Comment by Garr-R** [comment]
Welcome to installing Raspberry Pi images...? It always wipes your SD card

**Comment by guysoft** [comment]
This is expected behavior. Octopi is an image which is written on the sd card. Erasing all the data on it
