### ISSUE TITLE
'src/build_dist' has a 'jq' dependency, but that is not specified in 'README.rst'.

### ISSUE THREAD

**Issue by kmtologist** [guysoft/OctoPi#819]
'src/build_dist' has a 'jq' dependency, but that is not specified in 'README.rst'.

After installing 'jq' to my Ubuntu 22.04 host, I was able to successfully complete the OctoPi build.

'jq' should be listed as a dependency.

**Comment by guysoft** [comment]
Its listed on the requirments section:
https://github.com/guysoft/OctoPi#requirements

> jq (part of CustomPiOS dependencies)
