### ISSUE TITLE
Official 7 Inch touchscreen not detected

### ISSUE THREAD

**Issue by LewisSpring** [guysoft/OctoPi#821]
#### What were you doing?

1. Connect Raspberry Pi Official 7 Inch Touch Screen before first boot
2. Install desktop environment using provided script via SSH
3. Attempt to control backlight brightness and interact with DE via touch

#### What did you expect to happen?
1. Touch works in the desktop environment
2. Backlight can be controlled via `/sys/class/backlight/...`
3. `evtest` command shows the touch input device

#### What happened instead?
1. The touch does not work
2. The backlight does not exist in `/sys/class/backlight/...`
3. `evtest` command does not show the touch input device

#### Did the same happen when running OctoPrint in safe mode?

Not applicable

#### Version of OctoPi

OctoPi* 1.0.0 (build 2023.07.20.144556) (New camera stack image)

#### Printer model & used firmware incl. version

Not applicable

#### Screenshot(s)/video(s) showing the problem:

```
octopi@octopi:/ $ sudo evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:      WEB CAM: WEB CAM
Select the device event number [0-0]: ^C
octopi@octopi:/sys/class/backlight $ ls
octopi@octopi:/sys/class/backlight $ 
```

#### Additional Information
I didn't have any issues with Buster based images.
I have checked all cables.
I have tried troubleshooting with existing information on the web with no luck.
I have reimaged the SD card as a troubleshooting step.

[x] I have read the FAQ.

Thanks!

**Comment by guysoft** [comment]
Not sure how to test this ATM, I have a official touchscreen but I have no time to set it up and to try boot, if anyone has any input that would help
