### ISSUE TITLE
Octopi install fails if the login id used is not 'pi' when the pi installer is run

### ISSUE THREAD

**Issue by mnewnham** [guysoft/OctoPi#838]
#### What were you doing?
An Octopi install using the Raspberry installer for Windows

1. Select the _**Raspberry 4 Pi Device**_
2. Select _**Octopi (Stable)**_
3. Select Storage Device
4. At the next dialog box select _**Edit Settings**_
5. Under the general settings change the username from _**pi**_ to _**pudding**_
6. Complete the install
7. Boot the pi device

#### What did you expect to happen?
When octopi is booted. the _**octoprint**_ daemon should start as normal

#### What happened instead?
The _**octoprint**_ daemon fails to start. This is because the installation does not tailor the _**~/oprint/bin/octoprint**_ script to set the correct location for python. The script expects to find _**python**_ in the _**/home/pi/oprint/bin**_ directory, but if the user name is changed during the installation as above to _**pudding,**_  Octoprint is installed in the _**/home/pudding/oprint**_ directory as is the symbolic link to python.

#### Script as installed
````python
#!/home/pi/oprint/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from octoprint import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
`````
#### Script as it should be
````python
#!/home/pudding/oprint/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from octoprint import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
````
#### Affected files
``
~/oprint/bin/octoprint 
~/oprint/bin/python
``

#### Did the same happen when running OctoPrint in safe _mode?_
Yes

#### Version of OctoPi
OctoPrint version : 1.10.3
OctoPi version    : 1.0.0

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by guysoft** [comment]
This has been fixed in the current nightly builds, ``~/oprint`` has been moved to ``/opt/octopi/oprint``
