### ISSUE TITLE
Time-lapse doesn't render...

### ISSUE THREAD

**Issue by TheZippyMan** [guysoft/OctoPi#90]
I just tried out the timelapse option on my Raspberry Pi 2 with the Raspy Cam. Everything works fine, but when the print finished, I get this error: WARNING - Could not render movie, got return code 1

I am running Version: 1.1.2-1-gbabbbf6 (master branch).

Can anybody help me? :(

**Comment by guysoft** [comment]
I recommend you report this to the OctoPrint issue tracker:
https://github.com/foosel/OctoPrint/issues

**Comment by TheZippyMan** [comment]
I figured out the problem... Had Z hop enabled...
