### ISSUE TITLE
Running 2 Raspberrys in one Network

### ISSUE THREAD

**Issue by TheZippyMan** [guysoft/OctoPi#94]
I got a little problem/issue...

I want to run two Raspberrys with OctoPi connected to one network. How is it possible, that I can connect to 
Raspy 1 with octopi1.local
Raspy 2 with octopi2.local
?

Thank you!

**Comment by guysoft** [comment]
Run the following commands on OctoPi to change the hostname:
This example changes the hostname from octopi to octopi1
```bash
echo "octopi1" > /etc/hostname
sed -i -e "s@octopi@octopi1@g" /etc/hosts
```

**Comment by TheZippyMan** [comment]
Worked! 
Thank you so much! :)

**Comment by nsidious9** [comment]
dumb question but where do I add this command?  I do not see a command prompt or shell access on my octopi.

**Comment by guysoft** [comment]
@nsidious9 Please use the community forum at https://discourse.octoprint.org/
