### ISSUE TITLE
Log for mjpegstreamer

### ISSUE THREAD

**Issue by arekm** [guysoft/OctoPi#96]
Please run webcam script like this:
````
sudo -u pi -s /bin/bash -c "exec /home/pi/scripts/webcamDaemon > /home/pi/.octoprint/logs/webcam.log 2>&1" &
````
so we will get some log with info on what is happening.

**Comment by guysoft** [comment]
I'm busy these weeks (seed round for my startup). If you can pull request it would get faster in to the nightlies.

**Comment by arekm** [comment]
Fresh log with each boot, not sure if we want to keep old entries, too (if so then > needs to be changed to >>).

**Comment by guysoft** [comment]
Thanks a lot :)
Next nightly should start in 2 hours from now. And will be visible here (broken untill it starts): 
http://gnet.homelinux.com:8080/job/OctoPi/145/
When its done you welcome to try it out.

**Comment by guysoft** [comment]
Should be now in nightly, would appreciate if someone can confirm.

**Comment by foosel** [comment]
New webcamd now logs to /var/log/webcamd.log and has logrotate enabled.

@guysoft can we close this or do you want to keep it open until release of 0.12?

**Comment by guysoft** [comment]
Closed, and updated the release draft with this issue number.

**Comment by OutsourcedGuru** [comment]
For what it's worth, I'm not seeing the `/var/log/webcamd.log` on **1.4.0rc3 running on OctoPi 0.17.0**.
