### ISSUE TITLE
In OctoPrint, I'm unable to connect tto the printer

### ISSUE THREAD

**Issue by tbolt9000** [guysoft/OctoPi#99]
I have tried two different versions of Octopi with the same results..

I get the error:

Machine State: Error: Failed to open serial port. Check permissions?

**Comment by tbolt9000** [comment]
Messages in terminal window below:

Changing monitoring state from 'Offline' to 'Opening serial port'
Connecting to: None
Unexpected error while connecting to serial port: None OSError: '[Errno 2] No such file or directory: 'None'' @ comm.py:_openSerial:948
Changing monitoring state from 'Opening serial port' to 'Error: Failed to open seria...'

**Comment by nophead** [comment]
You need to select the correct serial port and baud rate. E.g. /dev/ttyUSB0 or /dev/ttyACM0.

**Comment by tbolt9000** [comment]
You are right.

 

I had just figured that out.

 

Thanks,
